### ISSUE TITLE
Domoticz WebUI asking for password

### ISSUE THREAD

**Issue by emontnemery** [domoticz/domoticz#2251]
Suddenly, Domoticz seems to ask for password a lot.
Has there been some change to http authentication recently?

**Comment by gizmocuz** [comment]
Yes there have been some changes, the latest one here:

https://github.com/domoticz/domoticz/pull/2223

I assume you entered an administrator username/password in the settings ?

If yes, then in your local network, did you enter the machine's IP address (or wildcard) that should not ask for a username/password ?

**Comment by gizmocuz** [comment]
The remember me functionality was broken, fixed here:

https://github.com/domoticz/domoticz/pull/2250

Would be in a new beta the next hour

**Comment by gordonb3** [comment]
Yes. Sorry about that. I didn't quite like how connections were logged, which was just once for as long as Domoticz was running and only logged the actual IP connecting even if that was acting as a proxy for another IP. I got thrown on the wrong foot though because there happen to be two timeout mechanisms active on sessions, which I still don't really get the point about but the fact is that I missed that second one and I killed the restore function that it relies on.

Can you confirm that it is fixed now?

**Comment by sweetpants** [comment]
Hmmm, some of my locally running scripts which where running before are having problems with authentication now (HTTP Error 401: Unauthorized)

Edit: Found it, that particular script did not use localhost, but the actual IP address

**Comment by gordonb3** [comment]
@sweetpants 
Can be tricky alright. Localhost and external IP are not the exact same beast. Don't really understand how my changes could have caused this though. I have tested this with a script running from both local machine and a different machine within "Local Network" and they both ran without issues.

**Comment by sweetpants** [comment]
Try this script on your domoticz server either with 'localhost' or the "IP address" of the domoticz server. The one with 'localhost' works, but fails with IP address (401)
`
#!/usr/bin/env python
import sys
import urllib2
domoticzserver = "192.168.24.250:8080"
switchplan_url = 'http://'+domoticzserver+'/json.htm?type=devices&plan=16'
def main():
    request = urllib2.Request(switchplan_url)
    response = urllib2.urlopen(request)
    r = response.read()
if __name__ == "__main__":
    sys.exit(main())
`

**Comment by emontnemery** [comment]
@gordonb3 The issue reported by me is indeed fixed. Should I close this issue, or keep open for the possibly related issue reported by @sweetpants ?

**Comment by gordonb3** [comment]
I think it would be best for sweetpants to open his own issue rather then piggyback on this one

Must also note that I can not replicate that issue on my version (3.9116 + cWebem patches). It may be work from another contributor that is causing this, or it may be related to settings (local networks?)
