### ISSUE TITLE
SetpiontTemperature timers isn't show, and is not editable

### ISSUE THREAD

**Issue by ScorpionZZZ** [domoticz/domoticz#2284]
Setpiont Temperature timers data disappeared from interface. If press on key timers edit table is always empty, but domoticz.db have data about it, and timers works according to database

**Comment by MAkerboom** [comment]
I think this is also a problem with dataTables (#2269) fixed in next beta.

You can press `control+schift+i` and post the javascript errors, if any

**Comment by ScorpionZZZ** [comment]
v3.9185 problem is absent.
Thanks

**Comment by Olifant1990** [comment]
@ScorpionZZZ: If this issue is solved, you can close this issue I guess?

**Comment by ScorpionZZZ** [comment]
Safari desktop - ok
Safari mobile, Chrome mobile (iOS) problem still present

**Comment by MAkerboom** [comment]
I could reproduce your issue on the last beta and can confirm it's resolved now, also on chrome mobile.

I know it's hard to get a good refresh on mobile, the appcache is very persevererend. Try opening an in-private/incognito tab.

**Comment by ScorpionZZZ** [comment]
Yes, everything is ok now
