### ISSUE TITLE
main/EventSystem.cpp:1244: bad erase

### ISSUE THREAD

**Issue by dcb314** [domoticz/domoticz#2644]
domoticz.spec.out:[/home/dcb/rpmbuild/BUILD/domoticz-4.9700/main/EventSystem.cpp:1234] -> [/home/dcb/rpmbuild/BUILD/domoticz-4.9700/main/EventSystem.cpp:1244]: (error) Iterator 'itt' used after element has been erased.

Source code is

 m_eventtrigger.erase(itt);

**Comment by emontnemery** [comment]
Do you have some way to reproduce?

**Comment by dcb314** [comment]
No I don't. Code looks wrong to me and the fix is pretty obvious.

**Comment by emontnemery** [comment]
OK..
Line 1244 is not `m_eventtrigger.erase(itt);` though, it's this one:
`itt = m_eventtrigger.erase(itt) - 1;`
The issue is the -1, and the solution is to convert to while loop, like below?
```
auto itt = m_eventtrigger.begin();
while (itt != m_eventtrigger.end())
{
	if (itt->ID == ulDevID && itt->reason == reason)
	{
		if (atime >= itt->timestamp)
		{
			m_eventtrigger.erase(itt);
			return (!bEventTrigger ? true : false);
		}
		else
			itt = m_eventtrigger.erase(itt);
	}
	else
	{
		itt++;
	}
}
```

Did you get more errors from cppcheck?

**Comment by dcb314** [comment]
Hundreds. Too many to list here. I suggest you could download a copy
of cppcheck and try it for yourself. 

Here are some more, performance this time.

/domoticz-4.9700/hardware/USBtin_MultiblocV8.cpp:456]: (performance) Passing the result of c_str() to a function that takes std::string as argument no. 3 is slow and redundant.
domoticz-4.9700/hardware/USBtin_MultiblocV8.cpp:457]: (performance) Passing the result of c_str() to a function that takes std::string as argument no. 3 is slow and redundant.
[domoticz-4.9700/hardware/USBtin_MultiblocV8.cpp:458]: (performance) Passing the result of c_str() to a function that takes std::string as argument no. 3 is slow and redundant.
/domoticz-4.9700/hardware/XiaomiGateway.cpp:544]: (performance) Passing the result of c_str() to a function that takes std::string as argument no. 4 is slow and redundant.

**Comment by emontnemery** [comment]
OK, but is my understanding of the `(error) Iterator 'itt' used after element has been erased.` correct: the code is actively working against m_eventtrigger.erase() returning the next element, and the solution is to convert to a while loop instead of a for?

**Comment by gizmocuz** [comment]
@dcb314, maybe it is possible to contribute your solution to the above issues with a pull request instead of quoting cppcheck ?

**Comment by dcb314** [comment]
Possible, but not going to happen.

I just find problems in packages, I leave suitable solutions to the domain experts,
i.e the maintainers.

**Comment by gizmocuz** [comment]
Thanks! that's what i thought

Anyway, warning corrected in:
https://github.com/domoticz/domoticz/commit/77917fd7da445a89b077e59988aa4d8232da97f1

@emontnemery , example code:

```
#include <vector>

struct _tMyStruct
{
	int ID;
	time_t mtime;

	_tMyStruct(const int iID, const time_t tTime)
	{
		ID = iID;
		mtime = tTime;
	}
};

int main()
{
    std::cout << "Hello World!\n"; 

	std::vector<_tMyStruct> m_items;

	m_items.push_back(_tMyStruct(1, 1000));
	m_items.push_back(_tMyStruct(2, 300));
	m_items.push_back(_tMyStruct(3, 600));
	m_items.push_back(_tMyStruct(3, 1200));
	m_items.push_back(_tMyStruct(3, 1800));
	m_items.push_back(_tMyStruct(4, 100));
	m_items.push_back(_tMyStruct(5, 100));

	_tMyStruct new_item(3, 800);

	//Going to remove all items with a larger timestamp

	for (auto itt = m_items.begin(); itt != m_items.end(); ++itt)
	{
		if ((itt->ID == new_item.ID) && (itt->mtime >= new_item.mtime))
		{
			m_items.erase(itt--);
		}
	}

	m_items.push_back(new_item);

	std::cout << "Goodbye World!\n";
}

```

**Comment by emontnemery** [comment]
@gizmocuz Maybe no warnings, but the modified code doesn't make sense, or maybe I don't understand it.
Why do you decrement the iterator after the erase?
Doesn't the original issue picked up by cppcheck still exist: Using the iterator after the element has been erased?

I really think the for loop is not appropriate when erasing elements, and should be converted to a while loop, something like:
```
auto itt = m_eventtrigger.begin();
while (itt != m_eventtrigger.end()) {
{
	if (itt->ID == ulDevID && itt->reason == reason && itt->timestamp >= atime) // cancel later or equal queued items
	{
		itt = m_eventtrigger.erase(itt);				{
	}
	else
	{
		itt++;
	}
}
```

**Comment by gizmocuz** [comment]
Did you check the sample ? (Hence the sample code)

**Comment by emontnemery** [comment]
Yeah, I checked the sample and I find it quite hard to read:
```
for (auto itt = m_items.begin(); itt != m_items.end(); ++itt)
{
	if ((itt->ID == new_item.ID) && (itt->mtime >= new_item.mtime))
	{
		// Decrement the iterator after the erase, so that we increment past the erased element at the next loop iteration
		// OK to keep using the iterator  after the erase() because the post-fix decrement returns a copy of the original iterator which is invalidated by erase()
		// If the iterator was at m_items.begin(), still OK to decrement it becuase it's incremented again before being dereferenced
		m_items.erase(itt--); 
	}
}
```

I'd suggest to do like this instead:
```
m_items.erase(std::remove_if(m_items.begin(),
                             m_items.end(),
                             [new_item](_tMyStruct t){return (t.ID == new_item.ID) && (t.mtime >= new_item.mtime);}),
              m_items.end());
```

**Comment by emontnemery** [comment]
@dcb314 Would you mind explaining in some detail how you run cppcheck on the Domoticz source tree?

**Comment by gizmocuz** [comment]
Why ? Did you checked that the correct items are removed ?

**Comment by gizmocuz** [comment]
@emontnemery , from what i see in @dcb314 's github history, he's not a developer but know how to run cppcheck, that would also explain his answers/reaction

**Comment by emontnemery** [comment]
@gizmocuz Yeah, understand, but I got errors from cppcheck when running it on the Domoticz source tree:
- If using cmake project file, there is some issue with python includes, and cppcheck does not work at all
- If just throwing cppcheck the source tree, it bugs out on some LUA struct types

And yes, I did test this on your example, and it is working fine (correct items removed):
```
m_items.erase(std::remove_if(m_items.begin(),
                             m_items.end(),
                             [new_item](_tMyStruct t){return (t.ID == new_item.ID) && (t.mtime >= new_item.mtime);}),
              m_items.end());
```

**Comment by gizmocuz** [comment]
@emontnemery , so my patch works correctly and does not need to be changed.
Meaning, we can close this issue right ?
There was a reason why i did not use std::remove_if ... anyway, there are many roads to Rome
I just open CPPChecker (windows), open the Domoticz folder (or specifically the main/hardware folder) and it starts checking

**Comment by emontnemery** [comment]
Yes, It can be closed if you fix the same issue also `CEventSystem::GetEventTrigger()` in addition to what was fixed in `CEventSystem::SetEventTrigger()`

Yes yes, many ways to Rome.. :)

**Comment by emontnemery** [comment]
@gizmocuz I have been looking at this a bit more today, and I'm starting to think there was no error to begin with but this is due to bugs in cppcheck.

What was really wrong about the line cppcheck complained about: `itt = m_eventtrigger.erase(itt) - 1;`?
I started a thread in the cppcheck forums: https://sourceforge.net/p/cppcheck/discussion/general/thread/f5de1f68/ ..

**Comment by gizmocuz** [comment]
@emontnemery , there was no error to begin with, @dcb314 just copied / pasted the cppcheckers message.
That's why i asked him to make a PR.

Still i will try to remember the 'm_items.erase(std::remove_if' approach for the feature ;)
