### ISSUE TITLE
Trigger user variable with on

### ISSUE THREAD

**Issue by Xenomes** [domoticz/domoticz#2904]
Hi,

I discover a little bug (I think). I was programming a blocky script and i used a user variable to write a value for a other script to check it has run. Then i test-run the script a light in the house when on. This is a test script to see if my theory was right, it was. My version is 4.10.266 running on a Pi3B+ with Ubuntu Mate.

Here my test script:
![afbeelding](https://user-images.githubusercontent.com/11648297/49685091-9f2c5800-fadd-11e8-9c65-f99b09ea5cd5.png)

There the user variable used:
![afbeelding](https://user-images.githubusercontent.com/11648297/49685166-ef57ea00-fade-11e8-9ce7-ecb083ea4c82.png)

There the light which went on:
![afbeelding](https://user-images.githubusercontent.com/11648297/49685129-2b3e7f80-fade-11e8-9587-d334694d4755.png)

The issue is in the matching IDX numbers or that I used the ON command in a user variable. I used the ON/OFF that it was a quick way the set i up :-).

Greetings Xenomes

**Comment by gizmocuz** [comment]
I still don't know what went wrong ?
But as you are using a string uservariable, you have to write a string

**Comment by Xenomes** [comment]
The value after the run is "On" so that works correctly. The stable version had the same issue.
![afbeelding](https://user-images.githubusercontent.com/11648297/49686441-f558c580-faf4-11e8-9be3-da030de0b4fe.png)
It looks like that the idx is called and then looses the origan of the idx or always looks in the hardware table.

**Comment by gizmocuz** [comment]
I still don't see whats the problem and how this relates to the idx ?

**Comment by sweetpants** [comment]
I have tested this with exactly the same setup, although my uservariable has idx=14, both "On" or a string works fine. idx=14 in my hardware table is a Darksky device. So what's the problem? Hardware idx and uservariable idx are not the same thing

**Comment by Xenomes** [comment]
That is strange, maybe it is RFLink related, there is no big problem. I used a text string in my original program, that works fine. I only want my share the discovery so the developer can check the code and improve the program.

**Comment by gizmocuz** [comment]
You need to give a better explanation what (according to you) is not correct.
I  normally never say this, but please try it in your native language:
- wat wil je doen ?
- wat gaat er volgens jou niet goed ?
- wat had er moeten gebeuren ?

**Comment by Xenomes** [comment]
Wat ik wilde was de waarde 'ON' in een variabel wegschrijven om deze in een andere script weer te kunnen gebruiken. Toen ik dat teste ging er een lamp aan deze had achteraf de zelfde idx, teste verder ook met 'OFF' ging hij uit terwijl die niet door een script word aangesproken.
Wat er volgens mij niet goed gaat is dat het commando richting variabel bij de hardware uitkomt en daarom deze dan schakelt. 
Mijn gedachte gang was de de waard 'ON' in de variabel als tekst op te slaan. Maar de test bij sweetpants gebeurt het bij hem niet, misschien ligt het aan mijn installatie. Het is voor de rest geen probleem gebruik nu een 1 of 0 in mijn scripten. Vond het raar en dat wou ik even melden.

**Comment by gizmocuz** [comment]
I think you needed to translate the string value of the variable "On" to 1, the 'state' of a switch is numeric
If you make a integer user variable it should give you the result that you wanted
But a look at your 'other' blockly where this variable is used could also be handy

**Comment by Xenomes** [comment]
I already converted the variable to integer the overlapping script are working perfectly.

**Comment by sweetpants** [comment]
I think I know what @Xenomes means. I have a uservariable with idx 14 and a light (RFLink) with idx 14. When you choose the logic 'On', it will turn On the light.

**Comment by gizmocuz** [comment]
Yep, now i see.... that should indeed not happen...  
It is because in the database (EventRules table), there where actually two commands being created
Fixed in upcoming beta (10267)

**Comment by sweetpants** [comment]
Thnx

**Comment by Xenomes** [comment]
Thnx! Sorry that my story was not very clear. You have solved it, that was the main thing.

**Comment by gizmocuz** [comment]
@Xenomes , it was a bit clear but it sounded really strange.... but when i looked at the code, it made perfect sense ! ;) thanks for reporting

**Comment by Xenomes** [comment]
Hi,
I tested the new build 4.10267, i am sorry to say but the issue still exist. :sweat_smile:
![domoticz](https://user-images.githubusercontent.com/11648297/49735855-bce9f080-fc88-11e8-95af-9ef6a5ab619f.gif)

**Comment by gizmocuz** [comment]
Could you clear the appcache and browser cache and try again ?
also try with a browser in private mode
you might need to create the event again

**Comment by sweetpants** [comment]
Should work if you re-create the event again.

**Comment by Xenomes** [comment]
I had clear the app cache and browser cache and then recreate the event the issue still excited, but after the update to 4.10.268 the issue is solved.
Thnx all for fixing!! (Spoiler I think I have found another one :grin:)

**Comment by gizmocuz** [comment]
@Xenomes , please do tell ;)

**Comment by Xenomes** [comment]
@gizmocuz Saturday morning I will post it, I have now a problem with OTGW... :confounded:
