### ISSUE TITLE
Yeelight, Mi-Light, Xiaomi Set Level / Set Color vs Kaku Set Level: 35%

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#3154]
Currently running Domoticz V4.10395.

It came to my attention that when using the Devices in the Domoticz Web application or by calling them via JSON url as described in the manual the followin log is shown:

For YeeLight  -> Set Level
For Mi-Light / YeeLight XIAOMI RGB Gateway -> Set Color
For Kaku Dimmer -> Set Level: xx%

It seems Kaku Devices does it correctly and the others don't. Can this be corrected?
The Data is stored correctly in the Domoticz Database, however the log IMO is wrong. And guess what.. :-) For Kaku devices I am able to retrieve the current dimming value, or the others I recieve just Set Level or Set Color.

![Bug Set Level](https://user-images.githubusercontent.com/5776333/56425764-f6c1a800-62b5-11e9-9604-ebab2d48603f.jpg)

**Comment by gizmocuz** [comment]
Thanks for reporting, fixed in beta 10676

**Comment by sincze** [comment]
Solution works excellent via the Dasboard icons or th API calls. ;-) tnx.
`switchcmd=Set%20Level&level=6`

If called via a different API call.
`/json.htm?type=command&param=setcolbrightnessvalue&idx=****&hue=274&brightness=40&iswhite=false`

The log still shows Set Color without the specified brightness level. Can we add the level to that log entry as well?
![Domoticz Set Color](https://user-images.githubusercontent.com/5776333/59973411-f5577900-959f-11e9-971d-228498c5ef52.JPG)

I'll need to create a new issue for that?
