### ISSUE TITLE
OZW: Unhandled Label: Smoke Alarm

### ISSUE THREAD

**Issue by remcom** [domoticz/domoticz#3254]
In V4.10806 (and probably earlier versions?) smoke alarms does not work anymore.

For existing devices the smoke switch is never triggered and the smoke alarm value doesnt change. On new devices the alarm isnt generated.

On start domoticz report
`2019-05-22 09:03:11.235 Status: OpenZWave: Value_Added: Unhandled Label: Smoke Alarm, Unit:`

**Comment by remcom** [comment]
Today or tomorrow 1 will recieve a few new smoke sensors so i can use one for my test setup. Then i will do some debugging with VS

**Comment by gizmocuz** [comment]
@RemCom , great thanks ! Should be found (OpenZWave.cpp line 1782, GetIndexFromAlarm)

**Comment by remcom** [comment]
@gizmocuz Thnx for the pointer I already found where to look. Didnt had much time yesterday to look at it but find out that both Smoke and Smoke Alarm label is received. When is add Smoke alarm i can get rit of the errors but still no alarm is generated of the switch smoke is triggered.

This evening i have the time to really look in to it

**Comment by gizmocuz** [comment]
you might get a new switch
when you enable debug logging for OZW, do you see an update when smoke is detected? (ozw log in the config folder)

Maybe we need to change the function "GetIndexFromAlarmType"

and search for the string with this;

```
unsigned char GetIndexFromAlarmType(const std::string& sLabel)
{
	int ii = 0;
	while (!AlarmTypeToIndexMapping[ii].sLabel.empty())
	{
		if (sLabel.find(AlarmTypeToIndexMapping[ii].sLabel) != std::string::npos)
			return AlarmTypeToIndexMapping[ii].iIndex;
		ii++;
	}
	return -1;
}

```

this way it will find "Smoke" and "Smoke Alarm" or "Smoke whatever"

I have updated the code a bit, could you try ?

**Comment by remcom** [comment]
I will test it but it will be Sunday at the earliest I think (being a little busy lately). I had it fixed locally and you indeed get a new switch. The issue is that is still don't receive any status from the smoke sensor when i tested the alarms. Could be there is an other issue or my fix is not totally correct. When i test the alarm no update notification is received at all. 1 had i working once after changing almost all the setting of the smoke detector but i couldn't reproduce it.

**Comment by remcom** [comment]
@gizmocuz Took me a little to find time again. You fix doesn't work for me. Still the same alarm. Only when i add smoke alarm in the list its added and i get a new switch.

Big problem still is that i do not receive any alarm from the smoke alarm when i run the test. Also no messages in ozw log. Other alarm like tamper are working fine. I almost expect some issue in the configuration file in openzwave.

**Comment by remcom** [comment]
These are the OZW log and cache file after adding the node. When you look in the cache file. On line 238 we see the label Smoke Alarm on index 1 and on line 471 the the label Smoke is used on that index. Don't know if that should be the same? Cant really find out in the OZW code where this is generated. Also cant test with other brands because i only have a fibaro smoke detectors.

[OZW_Log.txt](https://github.com/domoticz/domoticz/files/3229320/OZW_Log.txt)
[ozwcache_0xef1b1f40.txt](https://github.com/domoticz/domoticz/files/3229324/ozwcache_0xef1b1f40.txt)

**Comment by petergebruers** [comment]
Hi! I recently started working on the OZW code to help @Fishwaldo and right now I am going through the definitions and translations of the Notification class. I cannot fully answers questions yet but I can say OZW 1.6 is quite different compared with 1.4. I can tell you which files are involved.

config/Localization.xml
config/NotificationCCTypes.xml

And
cpp/src/ValueIDIndexesDefines.def which generates cpp/src/ValueIDIndexesDefines.h

To illustrate that, I have a PR to fix some typos

https://github.com/OpenZWave/open-zwave/pull/1817

Also, there are newer Notification types, I still have to make a PR. But this does not affect "Smoke Alarm"

The source of that information is in de the public Z-Wave spec, SDS13713 Notification Command Class, list of assigned Notifications.

To be honest, I have not yet "used" the ValueIDIndexesDefines myself. But I think as long as you match on ID (so not on label text because that might be translated) it should work.

Regarding the different wording in the ozwcache file, line 238 is for the "Alarm" class. That class is called "COMMAND_CLASS_NOTIFICATION" nowadays but you'll see "Alarm' everywhere. Then line 471 is for a different class, COMMAND_CLASS_SENSOR_ALARM. I cannot tell you much more about it than what is in the public spec, in SDS13781, Z-Wave Application Command Class Specification: "A device MAY implement this command class, but it is RECOMMENDED that new implementations use the Notification Command Class.". I would say "new" is relative, it is possible that the Fibaro Smoke sensor implements both for compatibility reasons (when it was designed).

**Comment by gizmocuz** [comment]
@petergebruers , thank you for this !!

Yes i know i have to start using the ValueIDIndexex and will soon (already started a little)
But still i think there is more to do. For example, take the **ValueID_Index_CentralScene**
We receive a Scene_1, but the state of the key (which you have to retrieve by calling **GetValueListSelection**, you can't check against an enum (as far as i know ?)
You have to look at the OZW source code for this
Which is even more confusing if you compare **c_CentralScene_KeyAttributes** against **CentralScene_KeyAttributes** ... and **createSupportedKeyAttributesValues** and so on


Sure I understand the spelling corrections, perfect !, But translation ? Does not seem quite right to me.
As explained in another issue, this does not make sense. We need 1 standard language in definitions, and for the moment, this must be English.
It really does not make any sense to translate "Carbon Monoxied (.. monoxide)" by a driver (OZW)...
Sure if an "application" wants to do this fine. 

You also do not want to end up with a 'driver' that has thousands of translations in hundred languages that also all have to be maintained.
Imagine the PR's , commits and merges... It's already a .... problem .... differentiating changes to code (wish I am interested in), and changes in Configuration files (wish users are interested in)
But that is my two sends... ;)

**Comment by gizmocuz** [comment]
@petergebruers , do you know how to use ValueID_Index_Meter ? I do not see any reference to index from labels Energy/Power/Voltage/Current/Power Factor/Gas/Water and so on

**Comment by Fishwaldo** [comment]
> But translation ? Does not seem quite right to me.
As explained in another issue, this does not make sense. We need 1 standard language in definitions, and for the moment, this must be English.

That's absolute rubbish. I have been saying since I started maintaining OZW "DO NOT USE LABELS TO IDENTIFY VALUEID's" and you have been, and now complaining of the additional work now after ignoring my previous advice. 

There are a few billion people in the world that are not native english speakers or the applications are targeted at non-native english speakers (Jeedom, Wulian, Chuangke to name a few). The Labels are intended for display to end users, not as a API. 

As for a Library maintaining translations, just have a look in your /usr/share/locale/ directory on any standard linux distribution and I think you will find that this is quite acceptable and in fact, on more "core" libraries, is mandatory. 
  
>Imagine the PR's , commits and merges... It's already a .... problem .... differentiating changes to code (wish I am interested in), and changes in Configuration files (wish users are interested in)
But that is my two sends... ;)

Maintaining config files is a OZW problem... not yours. The fact that *you* choose to bundle OZW source code into Domoticz and not use a submodule or external dependency is what is causing you additional work, and we did not force you into this.

**Comment by Fishwaldo** [comment]
> @petergebruers , do you know how to use ValueID_Index_Meter ? I do not see any reference to index from labels Energy/Power/Voltage/Current/Power Factor/Gas/Water and so on

As stated previously - The Meter CC will adopt the same approach as the Notification CC. That means its Values and Lists are going to be driven by XML files, rather than code. The reason is that the Spec's update these CC often with new types of Events/Sensors etc. You may want to think about how you handle this in Domonticz moving forward. In OZW, our aim is reduce the need to do new releases for these CC just to keep upto date with the Specs. (and thus actually reduce our effort). 

As it stands right now, the Meter Class is "Dynamic" in terms of how each ValueID Index is computed (mainly driven by the device). So what might be index 1 on a node from qubino, might be index 4 on a device from Aeotec. (or even from same vendors).

So its impossible for me to say Index 1 is Electricity as its driven by the device and interview process right now. 

The Meter, Indicator and MultiLevel Sensor CC are all going to move to the same "dynamic" CommandClass as the Notification CC soon.

**Comment by gizmocuz** [comment]
@Fishwaldo , as mentioned 'my two cents', no need to flame... no harm intended !
I also started saying i should use the index, that i was busy with it, and i just made quite a large commit doing so...

I am happy to use your library, i totally do not understand bundling OZW code into Domoticz ? Sure zwave is a sub module/class inside Domoticz, why would i need an external dependency ?
Even so, should that external dependency not have the same issues ?

Currently the biggest challenge is indeed the Meter command class. I understand your problem, but is it not somehow possible to generate a stable index ? For example when you use the label "Water" or "Voltage" you might be able to predict it's meter_type ?

**Comment by gizmocuz** [comment]
@RemCom, is it possible to try beta 10854+ to test if this solved (OZW: Unhandled Label: Smoke Alarm)

> Big problem still is that i do not receive any alarm from the smoke alarm when i run the test. Also no messages in ozw log

There is no single log line when you test it ? I would suspect so.... 

A smoke sensor just arrived and was able to test. When i press the test button i do receive a new switch/alarm, that is cleared after a second, and a smoke alarm clear event is fired.
Be sure to have accept new hardware is enabled in the settings while testing

**Comment by remcom** [comment]
@gizmocuz The fix for the Unhandled label is oke. But still no alarms for me when i test. I removed it. Reset the smoke detector. Readded it (as secure). And when i test i receive nothing. Not one line in the OZW log.

To be sure I'm going to grab another one from the main system to rule out the one that i'm testing with is faulty.

**Comment by remcom** [comment]
Same on the other device. Do you have a Fibaro and changed something in the settings to have it work?

**Comment by gizmocuz** [comment]
@RemCom , no i have tested it against a Heiman smoke detector.
I don't think this is Domoticz related.
What happens when you create some ?... like a tosti thats burning ;)

**Comment by remcom** [comment]
@gizmocuz Set some paper on fire and the i received the alarm. so conclusion, the test alarm isn't being send anymore. But that's probably OZW related, it worked in the past. Finally no testing any more with the fire alarm. It hurts your ears :P

**Comment by petergebruers** [comment]
I understand you don't want to test anymore, I own a few of them and I can confirm it hurts your ears :P - to see if it is OZW related it would be nice to have a OZW_Log.txt. I cannot test right now for several reasons, the most important one is they are included on my HC2.

BTW you can buy "test smoke" in a can, which I highly recommend, because it avoids the problem of contaminating the detection chamber with soot particles.

**Comment by remcom** [comment]
@petergebruers I actually have a have a canister of test smoke but i cant find it any more. I can make a test log for you. I will survive one test :P. What would you lite to see in the log? If i do a test nothing is entered in it. shell i add the node and after its added make the a test? I think i also did that in the log added in comment https://github.com/domoticz/domoticz/issues/3254#issuecomment-496651904

**Comment by petergebruers** [comment]
Actually, to be honest, the first thing I would like to test myself is to use Zniffer to see what device sends when you perform a self test. I assume this is the FGSD-002. And the manual says:

```
Self-test may be triggered manually:
1) Make sure the device is powered by the battery
2) Press and hold the B-button. The visual indicator will glow white and the short alarm will sound. Keep holding the B-button. After 3 seconds from the first beep smoke chamber operation will be checked.
Triggering fire alarm and beep mean positive result and should occur within 10 seconds. No fire alarm means that the sensor is malfunctioning.
```

The wording is a little bit ambiguous, what does "fire alarm" in this context mean, does it mean sounding the alarm and also send an alarm notification? Never tested that myself. But you seem to remember, at some time, the test alarm did trigger Domoticz, right? Maybe I should exclude the device and add it to Domoticz... And stop speculating 😄. But I am on holiday, cannot do that before next Monday.

**Comment by remcom** [comment]
It is indeed the FGSD-002. In the passed i saw in the OZW controlpanel that the Smoke Alarm changed to 'Smoke test' or something like that, cant recall and i have a flipped switch in domoticz. Currently i dont see anything in the log or in the OZW panel when i test the sensor.

It's no rush so enjoy your holiday :)

**Comment by petergebruers** [comment]
@RemCom Sorry for the delay. I ran Zniffer and you were not imagining it, The sensor sends an "COMMAND_CLASS_NOTIFICATION" of type "Smoke Alarm" and event "Smoke alarm test" when you keep holding the test button. It also sends the older CC, and even dutifully reports "tamper" because I have its battery cover removed.

This device is included on my Fibaro HC2, I need some time to test on Domoticz.

**Comment by gizmocuz** [comment]
@RemCom , could you try beta 10888 ? this should probably solve this issue (unhandled label)

**Comment by remcom** [comment]
@gizmocuz Sorry for the late response. I was on a holiday. The unhandled label error is indeed gone. Thnx for the fix!

@petergebruers oke. Let me know when you tested it on domoticz or if i can help you with some logging

**Comment by gizmocuz** [comment]
@RemCom , thanks for the feedback, i leave the issue open for you and peter to continue. Please close when possible

**Comment by petergebruers** [comment]
Tested on V4.10898, working fine...

Log: 2019-06-14 10:16:17.054  Status: OpenZWave: Alarm received (Smoke Alarm: Smoke Test)
BUI: Device "Alarm Type: Smoke Alarm 1 " has a column "Data", you'll see it display 0x03 which is Smoke Test.

**Comment by gizmocuz** [comment]
@RemCom , i would suspect you should also get a switch update as the smoke test is received.
Could you try the following, once all nodes are queried, delete all switches from this node
Next perform the test... do you get a new switch ?

**Comment by remcom** [comment]
@gizmocuz On 1.10891 Don't get a new switch . These are the switches that i have when i removed all and do a test. 


```
  |   | 1349 | z-stick | 00044B35 | 7 | Alarm Type: Home Security 7 (0x07) | General | Alarm | Event: 0x03 (3) | - | - |   | 2019-06-15 10:04:24
  |   | 1348 | z-stick | 00044B28 | 1 | General | Light/Switch | Switch | On | - |   |   | 2019-06-15 10:04:24
  |   | 1347 | z-stick | 00044B37 | 1 | System | Light/Switch | Switch | Off | - | - |   | 2019-06-15 10:04:15
  |   | 1346 | z-stick | 00044B36 | 1 | Power Management | Light/Switch | Switch | Off | - | - |   | 2019-06-15 10:04:15
  |   | 1345 | z-stick | 00044B35 | 1 | Home Security | Light/Switch | Switch | On | - | - |   | 2019-06-15 10:04:24
  |   | 1344 | z-stick | 00044B2C | 1 | Heat | Light/Switch | Switch | Off | - |   |   | 2019-06-15 10:04:24
  |   | 1343 | z-stick | 00044B29 | 1 | Smoke Alarm | Light/Switch | Switch | Off | - |   |   | 2019-06-15 10:04:24
  |   | 1342 | z-stick | 00044B00 | 1 | Sensor | Light/Switch | Switch | Off | - | - |   | 2019-06-15 10:04:14
```

I'm also surprised that i dont have a Alarm type for the smoke alarm

**Comment by gizmocuz** [comment]
@RemCom , i see a lot of switches there ? A smoke Alarm switch as well ? A sensor (Maybe from sensor alarm class) as well

**Comment by remcom** [comment]
Well the Fibaro smoke alarm always have generated these amount of switches. So thats not strange. In the past Smoke alarm was just Smoke. But in the past Both Heat and Smoke in the past gived also a Alarm Type Smoke and Heat. Those alarms are not generated. Even after a test with fake smoke (the smoke alarm switch does work then). But no response on test.

I even have a Heiman smoke detector smoke detector now. There i have alarm type and the test alarm and real test with fake smoke works as expected.

**Comment by gizmocuz** [comment]
I can also only test with my Heiman, and here it also works as expected.
Maybe the Fibaro is using Version 1 of the alarm class.
But do not only look at the switch states, only look at the date/time it is updated (as an alarm/alarm test) will only trigger a 'on'

**Comment by remcom** [comment]
I know from the switch state. also the last update timestamps doesn't show anything.

**Comment by gizmocuz** [comment]
@RemCom , but after the nodes are queried, and you delete all it's sensors from the devices tab, and you trigger a test/alarm, 'then' those new sensors are created... so it is strange you have them, that means that it is created

**Comment by petergebruers** [comment]
I wonder if things got changed after build 10891, I tested 10898, I always build from source. And most recent OZW master as well...

I have these devices:

```
Alarm Type: Smoke Alarm 1 (0x01) | General | Alarm | Event: 0x00 (0)
-- | -- | -- | --
Gas | Light/Switch | Switch | Off
Heat | Light/Switch | Switch | Off
Home Security | Light/Switch | Switch | Off
Power Management | Light/Switch | Switch | Off
Smoke Alarm | Light/Switch | Switch | Off
System | Light/Switch | Switch | Off
```

I have only tested the the first one, "Smoke Alarm", I have not focused on the other alarms

When I look at that table, shouldn't the other alarms also be of type "Alarm" and show events?



> Well the Fibaro smoke alarm always have generated these amount of switches.

Yes, it definitely supports all those alarms, eg "temperature alarm" is an alternative way of detecting fire.

**Comment by remcom** [comment]
I currently compiling the latest Domoticz (I also build from source). I cant test with the latest openzwave. I'm currently using the 339d53d commit fom 10 june. If I build the latetst Domoticz crashes after a few seconds in a segmentation fault.

I see you do have an alarm type for smoke thats different. I will do a quick test after my build is done.

**Comment by petergebruers** [comment]
BTW that table is what I get, after I have received a "Smoke Test" alarm and I don't know what it looks like *before* that. Maybe I should delete my Domoticz database, my ozwcache and try again.

**Comment by gizmocuz** [comment]
Please not that i just committed some changes and also accept unknown labels (labels are now used for backwards compatibility only, from a known label , it generates a index that was previously used)
Now, when a label is not known, we use the original Index value of the alarm event... 
Actually we should drop the label matching... but this generated new devices for all users.... but it might be for the best

@petergebruers , be sure to have enabled 'accept new hardware/devices' in the settings, you might get new devices

**Comment by gizmocuz** [comment]
Quick question, when you 'test' or fire the alarm, you do see updates in device type 'General/Alarm' ? (with data Event: xxxxx) ?
This because i need to do more work on this type of device. (support showing in the gui, notifications , triggers, etc)...
When that works, we could drop the generation of 'switches' ...

**Comment by remcom** [comment]
I now tested on 1.10906. When i do a test alarm no switches or alarm type gets a update.

When i test with smoke i only have a reaction on the switch no alarm type for smoke is generated.

**Comment by gizmocuz** [comment]
@RemCom , you mean you do have a reaction on the sensor General/Alarm ? I dont think there is a switch "No Alarm type"
But could you try to set breakpoints and debug to see what happens ?

**Comment by petergebruers** [comment]
My test strategy for this device is a bit special, I don't use a "real" device but I simulate an FGSD. This approach has pro's and cons. The main con is "it is not a real device" the pro is I can make it do whatever I want, eg pretend it is awake at startup, make it send any alarm after 30 seconds etcetera. Don't get too excited, it is an incomplete simulation but it allows me to simulate what @RemCom gets...

If I delete domoticz.db and ozwcache and I pretend my device is asleep after the "inclusion" process then I almost get what @RemCom sees: a bunch of "Light/Switch" devices and no devices of type "Alarm"

```
Gas
Heat
Home Security
Power Management
Smoke Alarm
System
```

Because I never really used Domoticz (sorry guys) I am unable to tell if this is what you want.

So now let's modify my similator en pretend this device is a awake, then OZW will query the alarm states and I respond by saying "The Smoke Alarm is clear".

When I restart domoticz (no deleting of files involved) domoticz creates a new device:
```
Alarm Type: Smoke Alarm 1 (0x01) | General | Alarm | Event: 0x00 (0)
```

So, again, never really used Domoticz but it seems plausible to me that this is recorded as an Alarm and status is "clear".

For the next test, I modify my simulator to do SendSmokeEvent(3); (that's test) and SendSmokeEvent(0); at regular intervals...

Now, for sure, the "Data" column starts showing these events
Event: 0x00 (0)
Event: 0x03 (3)

And the "Smoke Alarm" device (of type Light/Switch) starts toggling between "on" and "off".

Log:
```
2019-06-15 11:28:29.982  Status: OpenZWave: Alarm received (Smoke Alarm: Clear)
2019-06-15 11:28:29.984  (tttt) General/Alarm (Alarm Type: Smoke Alarm 1 (0x01))
2019-06-15 11:28:29.986  (tttt) Light/Switch (Smoke Alarm)
2019-06-15 11:28:35.334  Status: OpenZWave: Alarm received (Smoke Alarm: Smoke Test)
2019-06-15 11:28:35.336  (tttt) General/Alarm (Alarm Type: Smoke Alarm 1 (0x01))
2019-06-15 11:28:35.338  (tttt) Light/Switch (Smoke Alarm)
```

**Comment by petergebruers** [comment]
Previous test was on 10898, I've redone the last test (deleted domoticz.db, run simulator with alternating test/clear alarms) on V4.10901 and that version behaves in the same way.

**Comment by remcom** [comment]
@gizmocuz i dont have any reaction General/Alarm. If i run some debugging i dont even receive any values from openzwave when i do a smoke test. So that domoticz doesn't do anything is not that strange.

**Comment by gizmocuz** [comment]
@petergebruers , thanks for testing this!
If you start domoticz, domoticz will not create devices... only when they are triggered (via OpenZWave::Notification::Type_ValueChanged)
Which is what you want....

It seems when you let the alarm trigger, it indeed update also a switch (that should also be), when it is clear, the switch should be OFF, otherwise ON
In the case of an alarm (which is not specifically handled), the status update is done here:

OpenZWave.cpp , UpdateValue, line 2810 till 2819

```
					switch (intValue)
					{
					case 0x00: 	// Previous Events cleared
					case 0xfe:	// Unkown event; returned when retrieving the current state.
						intValue = 0;
						break;
					default:	// all others, interpret as alarm
						intValue = 255;
						break;
					}
```

intValue is generated above here:

```
			if (vType == OpenZWave::ValueID::ValueType_List)
			{
				if (m_pManager->GetValueListSelection(vID, &intListValue))
				{
					if (intListValue == 0)
						intValue = 0;
					else
						intValue = 255;
					m_pManager->GetValueListSelection(vID, &szListValue);
					_log.Log(LOG_STATUS, "OpenZWave: Alarm received (%s: %s)", vLabel.c_str(), szListValue.c_str());
				}
			}
```

Smoke Alarm: Clear = 0, rest threaded as 255

**Comment by petergebruers** [comment]
Okay, the switch then lumps together these alarms in the "on" state but that's OK I guess, the alarm events can give you the details.

```
Smoke detected (location provided)
Smoke detected
Smoke alarm test
Alarm silenced
Replacement required
Replacement required, End-of-life
Maintenance required, planned periodic inspection
Maintenance required, dust in device
```

@RemCom - I think you get the final word on this... You have said:

> @gizmocuz i dont have any reaction General/Alarm. If i run some debugging i dont even receive any values from openzwave when i do a smoke test. So that domoticz doesn't do anything is not that strange.

My simulator is based on what I "sniffed" from a real device, so I know the FGSD does send an "event 3" and OpenZWave decodes it.

So maybe the last question is... Is it possible your device does not send this event? If I remember correctly, it takes a while after entering test mode for it to sound the very loud alarm, but I couldn't say if it sends that event right away or after sounding the buzzer, and when it sends "clear". I did not pay attention, al I needed to know was that alarm smoke event 0x03. I cannot test that for you, my FGSD is on my Fibaro network.

**Comment by remcom** [comment]
@petergebruers I did a test on my 4 Fibaro smoke detection and 2 extually worked. Let me do some digging what is different with the other 2.

**Comment by gizmocuz** [comment]
@petergebruers , 

> the switch then lumps together these alarms in the "on" state but that's OK I guess, the alarm events can give you the details.

Yes it is, that is why i created a new sensor type General/Alarm, that does support all different event types. But I need to add more support for this throughout the system. It is also much cleaner then generating switches

@RemCom , That sounds a lot better! Could be a configuration issue... i have had some on my switches (like basic_set against On/Off)

**Comment by remcom** [comment]
All the configs are the same. But the 2 sensors that are working the group 1, 4 and 5 are connected to node 1 (the controller). On the sensors that i tested and connected later only group 4 and 5 are connected to node 1.1 (don't know what the second 1 is?). Also i dont seem to be able to set node 1 on group 1.

**Comment by petergebruers** [comment]
Long shot: are 2 of them the older model? From the  top of my memory type "FGSS"?

If that does not explain the difference, I'll make an issue on the OZW repo for you.

I think this issue can be closed.

**Comment by remcom** [comment]
All 4 of them are  FGSD002 also both Application and Protocol versions are the same.

I think indeed that the issue for domoticz can be closed

**Comment by petergebruers** [comment]
Thank's everyone for your time and providing valuable information.

Let's continue the issue about association groups on the OZW forum issue 1840

https://github.com/OpenZWave/open-zwave/issues/1840
