### ISSUE TITLE
Full access to Domoticz API  by using IP from CLI of domoticz server; bug or feature?

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4833]
Tested on build 13266 on Linux debian

More details in [Forum post ](https://www.domoticz.com/forum/viewtopic.php?f=28&t=36334)

"When I have users and passwords in Domoticz, no exceptions in 'Local Networks (no username/password):'  I do have full access to Domoticz by using IP address of first wired ethernet port when accessing it from the CLI of the  domoticz server."

as standard user from CLI on 192.168.192.115

```
curl "http://127.0.0.1:8084/json.htm?type=devices&used=true&displayhidden=1" -k # unauthorized = expected
curl "http://locahost:8084/json.htm?type=devices&used=true&displayhidden=1" -k # unauthorized = expected
curl "http://192.168.192.130:8084:8084/json.htm?type=devices&used=true&displayhidden=1" -k # (wireless IP) )unauthorized = expected
curl "http://192.168.192.115:8084/json.htm?type=devices&used=true&displayhidden=1" -k # authorized = Not expected


```
Same for https with https port number 

Check with previous release give all the expected results.

**Comment by JackV2020** [comment]
I would like to keep this as a feature. No security risk because you need to be on the domoticz server itself. It offers a very convenient way to do things from your plugins in domoticz like creating rooms etc. without the need to specify username and password. Please keep this as a feature. By the way it is general for http access. So when you use your webbrowser on your server and go to the IP of the host you need no user or password. When you use localhost or 127.0.0.1 you do need credentials. A good way to get in when you lost your admin password. Secure too because you first need to logon to your server.

**Comment by rwaaren** [comment]
I am not sure. Even without the need for root (or sudo) you can do a lot of harm with this and some servers host more apps then just domoticz. Being able to access the server does not imply you ought to be trusted with this kind of power and if you need it you can enforce this behavior already by entering the right values in "Local Networks (no username/password):"

btw. for recovering from a lost password situation you have the start option --nowwwpwd

**Comment by JackV2020** [comment]
So I understand it is best to forget this 'feature'. And to keep things working without entering details in "Local Networks (no username/password):" I best keep what I have in place nowadays which are 2 fields in the Hardware screen of my plugins where one can optionally enter an admin username and password ?
By the way thanks for the --nowwwpwd hint. I did not now about it and did not need it yet but will remember it one day... ;-)

**Comment by gizmocuz** [comment]
@JackV2020 , I also would not recommend you store the admin password for/in your plugin as well...
What are you trying to achieve that requires a admin level ?

**Comment by JackV2020** [comment]
@gizmocuz 
Here is an example of what I do in a plugin and which does only work when the Username and Password are of an admin account. A user with view or user rights are not able to do this. I verified this this morning once again, just to be sure.

Create a Room:

            url='http://'+IPAddress+':'+HTTPPort+'/json.htm?name='+RoomName+'&param=addplan&type=command'
            Domoticz.Log('Create Room '+url)
            response=requests.get(url, auth=(Username, Password))
            data = json.loads(response.text)

I have to do this this way because there is no documentation, as far as I know, other than the json descriptions on https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s  and 'the trick' to use the Network part of the Webdeveloper tool in Firefox to find the json calls. Other browsers will support 'the trick' too, but I am a Firefox user so this is what I use to get info on json calls.

It would be nice to be able to do this, and anything else, like you can create devices with Domoticz.Device(....).Create()

As long as I do not know how to do that I have to use the way I described above to create a room, add devices to the room.

Changing the code to get the IP address of the physical ethernet interface and not using Username and Password is not that difficult to do but as we agree, I think, this feature may fade away one day.

So maybe my question should be how to do 'anything' with methods like there are for Devices.

And by the way....

I do not store usernames or passwords in the plugins. They are entered on the Hardware page of the plugin where the password field is also masked as a password so you see only a row of little balls.
This way the Username and Password get stored in the database in the fields of the Hardware table. So when you know this and can get hold of the database, yes you can get hold of the usernames and passwords.

**Comment by gizmocuz** [comment]
@JackV2020 , The 'Settings' from a hardware plugin are not that safely stored and can be a risk when someone is able to extract your database.
I see you are creating a 'room', this can be done from the Domoticz GUI very easily.  Do you need to do this once ? What kind of plugin are you developing ?

**Comment by JackV2020** [comment]
@gizmocuz
(Please note that I mentioned the issue of storing the username and password in the last line of my previous post already.)
The plugin I am working on is for developers working on rooted Toon 1 / Toon 2.

You may know Toon from Eneco as a smart thermostat which is sitting on the wall of peoples living rooms.

The plugin has 6 buttons to reboot Toon, restart GUI, Start/Stop VNC server on Toon, Start/Stop GIU+APP Logging and a button to switch the Toon GUI mode between '4 small tiles + big heating' and '6 small tiles'

Next to these 6 buttons it produces 37 custom sensors with data for linux performance, environmental, internal thermostat stuff and name it.

To avoid the 'polution' of the rest of Domoticz I create a room with the name of the hardware implementation.

Further below you can see a screenshot for an implementation with the name 'Toon Monitor 2'.

So when you make some Harware implementations and name them 'Toon 1 Dev', 'Toon 2 Dev' and 'Toon Living' you end up with something like 3 x 6 = 18 buttons and 3 x 37 = 111 sensors which is a total of 129 devices. Nicely in 3 rooms with a clear name each.

This seems a lot but since screen layouts for Toon 1 and Toon 2 differ you need 2 Toons for development and 'someone' in the house may not like you anymore when you are developing on the Toon in the living room you end up with a 3rd Toon.

The current version in my github has about 17 custom sensors and does not have all sensors yet because I hope for the outcome of this to be a solution like: 
( I am sure you can come up with better but just to give an idea )

Domoticz.Room(RoomID, RoomName)Create()

Domoticz.Room(RoomID)Delete()

Room[RoomID].Add(DeviceID, OnPosition)

Room[RoomID].Remove(DeviceID [, OnPosition] )

Looping like

for Device in Room : if Devices[Room[RoomID][Device]['DeviceID']].Name =='SomeName' : ' do something'

would be nice too.
![image](https://user-images.githubusercontent.com/71119057/119221636-874fbf80-baf0-11eb-999b-fb243b034dd3.png)

**Comment by pipiche38** [comment]
Why not one plugin instance per Thermostat

**Comment by rwaaren** [comment]
Back on topic...


@gizmocuz. Investigated this a bit more and the changed behavior was introduced with #4136 

build <= 12057 
```
curl "http://192.168.192.115:8080/json.htm?type=devices&used=true&displayhidden=1"
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

Build >= 12060 allows API access without user- and password with below settings.

```
curl "http://192.168.192.115:8080/json.htm?type=devices&used=true&displayhidden=1"

{
        "ActTime" : 1621677310,
        "AstrTwilightEnd" : "00:00",
        "AstrTwilightStart" : "00:00",
        "CivTwilightEnd" : "22:19",
        "CivTwilightStart" : "04:51",
        "DayLength" : "16:01",
        "NautTwilightEnd" : "23:21",
        "NautTwilightStart" : "03:48",
        "ServerTime" : "2021-05-22 11:55:10",
        "SunAtSouth" : "13:35",
        "Sunrise" : "05:35",
        "Sunset" : "21:35",
        "app_version" : "2020.2 (build 12060)",
        "status" : "OK",
        "title" : "Devices"
}
```


![image](https://user-images.githubusercontent.com/24454798/119222664-b3217400-baf5-11eb-87fb-45b5b3d40306.png)

**Comment by JackV2020** [comment]
> Why not one plugin instance per Thermostat

It is 1 instance per thermostat put in an own room per termostat where the room gets the name of the Hardware instance.

**Comment by gizmocuz** [comment]
@JackV2020 , I think it's best to let the user create the group and add the devices. It is not a difficult task.
Looking at the devices, I think it's way to much! And also a lot of devices that are not of interest for 99% of the users.
Maybe for a toon developer point of view it is. (For instance the disk usage, cpu load etc)
But all of that info could be made visible with a application on the toon... 
Thermostat setpoint, room temperature, P1, switches, those things are of course of interest.
Restarting toon could be done via the Toon's own web gui (or via a application on the toon)

**Comment by gizmocuz** [comment]
@rwaaren, this is not possible, and you get a:

401 Unauthorized

Just tested this... make sure you have no cookies somewhere

**Comment by kiddigital** [comment]
@rwaaren , could you test the same problem with the branch of PR #4824 ?

I did some refactoring in the Auth code base.

**Comment by JackV2020** [comment]
@gizmocuz , many thanks for the feedback on what I would need to put in the plugin and what to put in an app on Toon. I will think about that.
About the topic, I modified the plugin to use 127.0.0.1 and now give the option to enter Admin credentials in the Hardware page but also point at the option to put 127.0.0.1 in 'Local Networks (no username/password):'. So I do not use the 'feature' anymore.
A final question since this is one of the things which causes me to use the json option and got us here in the first place is the next : 
Is there any chance that there will be methods to create and modify rooms like you can with devices one day ?
Or maybe better, a function like Domoticz.JSON(.....) returning json formatted data and opening all functionality which is now available via json, maybe using a kind of implicit admin access over 127.0.0.1 so everything is available from with plugins ?

**Comment by rwaaren** [comment]
> @rwaaren , could you test the same problem with the branch of PR #4824 ?
> 
> I did some refactoring in the Auth code base.

@kiddigital 
Compiling now. I will report back.

@gizmocuz 
I tested with curl on Debian > 10 different builds >= 13060 / fresh database and they all allow access this way. 
I tested with curl on Debian with 3 different builds <= 13057 / fresh database and they all give me unauthorized.
Above tests were in mixed order.

Please help me understand how cookies could interfere with my test results.

**Comment by rwaaren** [comment]
@kiddigital tried with PR4824 ;same result

@gizmocuz Added a bit of debug logging. 

started with a fresh database each run.

### build 13285 (PR from kiddigital)
```
./domoticz -sslwww 7443 -log domoticz.log -loglevel normal,status,error,debug -debuglevel normal,hardware,received,webserver,eventsystem,python,thread_id,auth
2021-05-23 14:31:57.254  [7f16f1986980] Status: Domoticz V2021.1 (build 13285) (c)2012-2021 GizMoCuz
2021-05-23 14:31:57.254  [7f16f1986980] Status: Build Hash: f05b1a781, Date: 2021-05-17 09:18:26
2021-05-23 14:31:57.254  [7f16f1986980] Status: Startup Path: /home/pi/pw/
2021-05-23 14:31:57.262  [7f16f1986980] Sunrise: 05:33:00 SunSet: 21:36:00
2021-05-23 14:31:57.262  [7f16f1986980] Day length: 16:03:00 Sun at south: 13:35:00
2021-05-23 14:31:57.262  [7f16f1986980] Civil twilight start: 04:49:00 Civil twilight end: 22:20:00
2021-05-23 14:31:57.262  [7f16f1986980] Nautical twilight start: 03:46:00 Nautical twilight end: 23:24:00
2021-05-23 14:31:57.262  [7f16f1986980] There is no astronomical twilight in the space of 24 hours
2021-05-23 14:31:57.299  [7f16f1986980] Status: PluginSystem: Started, Python version '3.9.2'.
2021-05-23 14:31:57.302  [7f16f1986980] Active notification Subsystems: (0/13)
2021-05-23 14:31:57.302  [7f16f1986980] Status: WebServer(HTTP) started on address: :: with port 8080
2021-05-23 14:31:57.304  [7f16f1986980] Status: WebServer(SSL) started on address: :: with port 7443
2021-05-23 14:31:57.305  [7f16f1986980] Starting shared server on: :::6144
2021-05-23 14:31:57.306  [7f16e7fff700] Status: TCPServer: shared server started...
2021-05-23 14:31:57.306  [7f16e6ffd700] Status: RxQueue: queue worker started...
2021-05-23 14:31:59.307  [7f16e67fc700] Status: NotificationSystem: thread started...
2021-05-23 14:31:59.308  [7f16e77fe700] Status: EventSystem: reset all events...
2021-05-23 14:31:59.308  [7f16e77fe700] Status: EventSystem: reset all device statuses...
2021-05-23 14:31:59.341  [7f16e77fe700] Status: Python EventSystem: Initalizing event module.
2021-05-23 14:31:59.341  [7f16e5ffb700] Status: EventSystem: Started
2021-05-23 14:31:59.341  [7f16e57fa700] Status: EventSystem: Queue thread started...

curl -vv "http://192.168.192.115:8080/json.htm?type=devices&used=true&displayhidden=1"
*   Trying 192.168.192.115:8080...
* Connected to 192.168.192.115 (192.168.192.115) port 8080 (#0)
> GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1.1
> Host: 192.168.192.115:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 424
< Cache-Control: no-cache
< Pragma: no-cache
< Access-Control-Allow-Origin: *
< Content-Type: application/json;charset=UTF-8
<
{
        "ActTime" : 1621773016,
        "AstrTwilightEnd" : "00:00",
        "AstrTwilightStart" : "00:00",
        "CivTwilightEnd" : "22:20",
        "CivTwilightStart" : "04:49",
        "DayLength" : "16:03",
        "NautTwilightEnd" : "23:24",
        "NautTwilightStart" : "03:46",
        "ServerTime" : "2021-05-23 14:30:16",
        "SunAtSouth" : "13:35",
        "Sunrise" : "05:33",
        "Sunset" : "21:36",
        "app_version" : "2021.1 (build 13285)",
        "status" : "OK",
        "title" : "Devices"
}
* Connection #0 to host 192.168.192.115 left intact

2021-05-23 14:32:12.510  [7f16ee612700] Debug: web: Host:192.168.192.115 Uri;/json.htm?type=devices&used=true&displayhidden=1 // first curl
2021-05-23 14:32:12.510  [7f16ee612700] Status: Incoming connection from: 192.168.192.115
2021-05-23 14:32:12.510  [7f16ee612700] Debug: [web:8080] generate new session id token b2d1328eda5964d363dfb696f9115433
2021-05-23 14:32:12.510  [7f16ee612700] Debug: [web:8080] generate new authentication token MGMzMDQ1ZWItMWU3Zi00NmJmLWJlM2YtMzQ1YmE3ZThhYzc1 for user
2021-05-23 14:32:57.302  [7f16eee36700] Debug: [web:8080] cleaning sessions...
2021-05-23 14:32:57.305  [7f16ede11700] Debug: [web:7443] cleaning sessions...
2021-05-23 14:33:12.827  [7f16ee612700] Debug: web: Host:192.168.192.115 Uri;/json.htm?type=devices&used=true&displayhidden=1 // second time curl

```

### build 12057
```
./domoticz -sslwww 7443 -log domoticz.log -loglevel normal,status,error,debug -debuglevel normal,hardware,received,webserver,eventsystem,python,thread_id
2021-05-23 14:40:41.753  [7f8730c32980] Status: Domoticz V2020.2 (build 12057) (c)2012-2020 GizMoCuz
2021-05-23 14:40:41.753  [7f8730c32980] Status: Build Hash: 096d786a2, Date: 2020-05-14 10:22:15
2021-05-23 14:40:41.770  [7f8730c32980] Status: Startup Path: /home/pi/pw/
2021-05-23 14:40:41.776  [7f8730c32980] Sunrise: 05:33:00 SunSet: 21:36:00
2021-05-23 14:40:41.777  [7f8730c32980] Day length: 16:03:00 Sun at south: 13:35:00
2021-05-23 14:40:41.777  [7f8730c32980] Civil twilight start: 04:49:00 Civil twilight end: 22:20:00
2021-05-23 14:40:41.777  [7f8730c32980] Nautical twilight start: 03:46:00 Nautical twilight end: 23:24:00
2021-05-23 14:40:41.777  [7f8730c32980] There is no astronomical twilight in the space of 24 hours
2021-05-23 14:40:41.808  [7f8730c32980] Status: PluginSystem: Started, Python version '3.8.7'.
2021-05-23 14:40:41.810  [7f8730c32980] Active notification Subsystems: (0/13)
2021-05-23 14:40:41.811  [7f8730c32980] Status: WebServer(HTTP) started on address: :: with port 8080
2021-05-23 14:40:41.813  [7f8730c32980] Status: WebServer(SSL) started on address: :: with port 7443
2021-05-23 14:40:41.814  [7f8730c32980] Starting shared server on: :::6144
2021-05-23 14:40:41.814  [7f87277fe700] Status: TCPServer: shared server started...
2021-05-23 14:40:41.815  [7f87267fc700] Status: RxQueue: queue worker started...
2021-05-23 14:40:43.816  [7f8725ffb700] Status: NotificationSystem: thread started...
2021-05-23 14:40:43.816  [7f8726ffd700] Status: EventSystem: reset all events...
2021-05-23 14:40:43.816  [7f8726ffd700] Status: EventSystem: reset all device statuses...
2021-05-23 14:40:43.842  [7f8726ffd700] Status: Python EventSystem: Initalizing event module.
2021-05-23 14:40:43.843  [7f87257fa700] Status: EventSystem: Started
2021-05-23 14:40:43.843  [7f8724ff9700] Status: EventSystem: Queue thread started...
2021-05-23 14:40:44.278  [7f872f6b2700] Status: PluginSystem: Entering work loop.


curl -vv "http://192.168.192.115:8080/json.htm?type=devices&used=true&displayhidden=1"
*   Trying 192.168.192.115:8080...
* Connected to 192.168.192.115 (192.168.192.115) port 8080 (#0)
> GET /json.htm?type=devices&used=true&displayhidden=1 HTTP/1.1
> Host: 192.168.192.115:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Length: 91
< Content-Type: text/html
< Set-Cookie: DMZSID=none; HttpOnly; Expires=Thu, 01 Jan 1970 00:00:00 GMT
<
* Connection #0 to host 192.168.192.115 left intact
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>


2021-05-23 14:41:00.386  [7f872d9a3700] Debug: web: Host:192.168.192.115 Uri;/json.htm?type=devices&used=true&displayhidden=1 // first curl
2021-05-23 14:41:32.747  [7f872d9a3700] Debug: web: Host:192.168.192.115 Uri;/json.htm?type=devices&used=true&displayhidden=1 // second curl
2021-05-23 14:41:41.811  [7f872e1a4700] Debug: [web:8080] cleaning sessions...
2021-05-23 14:41:41.813  [7f872d1a2700] Debug: [web:7443] cleaning sessions...
```

**Comment by kiddigital** [comment]
@rwaaren  , after a succesful login Domoticz sets a cookie called DMZID (see the resultdata from the Login page, for example when using the Dev-tools of your browser. Or try a tool like Postman.). You should see a separate return dataset in het Header of the response. Look for the 'Cookie' Header...

By default your browser will (re)send the Cookie with each request to the same domein and/or path within the Domain. You can see that as well through the Dev-tools within your Browser.

The Domoticz DMZID contains a reference to the Session, so each request that Domoticz receives that contains a Cookie (DMZID), it uses the value of the Cookie to retrieve the Session and see if it is an active- and valid session. If so, Domoticz will re-use that session and the user-information (incl. rights).

When logging out, the Cookie should be removed. If not and the browser remembers the Cookie and send it with a next request, the session will come alive again. Without the need to login.

The PR adds JWT as an option to Authenticate and does NOT use a cookie. An option that can be used by scripts or other (front-end) applictions. But not (yet) by the Domoticz UI. The current UI depends on the DMZID cookie.

**Comment by kiddigital** [comment]
@rwaaren (my previous reply was late, didn't see your previous response)...

The response of both build differ... the second one (12057) does return a 401 response code AND tries to (un)set the DMZID Cookie by setting the value to None (and the expire time in the past)

The PR build gives a 200 response, meaning that the request succeeded and a response is returned. Also it does not send out a cookie in the response.

In both cases you do not send a cookie in the request, which is ok. BTW (haven't checked) what is the expected response? As you did not login, should this request by accepted (200) or rejected (401)?

**Comment by rwaaren** [comment]
@kiddigital 
The expected result is **HTTP/1.1 401 Unauthorized.** (like it happens in all builds <= 12057) because there is no username/password in the curl call and domoticz should not allow any access to the system without these if it not explicitly configured by the setting in the field 
### Local networks (No username / password)

**Comment by kiddigital** [comment]
@rwaaren , and what happens if you try different commands like 'settings', etc.?

Because I think somehow Domoticz thinks this request is whitelisted.

Btw, in the PR build there is a new 'auth' debug level that shows Authorization related messages.

**Comment by rwaaren** [comment]
> and what happens if you try different commands like 'settings', etc.?
> Because I think somehow Domoticz thinks this request is whitelisted.
> 
> Btw, in the PR build there is a new 'auth' debug level that shows Authorization related messages.

I assumed something like that and that is why I tested that before but same result. I also used the auth debug (see one of my previous posts in this issue)


### build 13285 (PR from kiddigital)
```
2021-05-23 18:08:03.425  [7f0b2171a700] Debug: web: Host:192.168.192.115 Uri;/json.htm?type=settings
2021-05-23 18:08:03.427  [7f0b2171a700] Status: Incoming connection from: 192.168.192.115
2021-05-23 18:08:03.427  [7f0b2171a700] Debug: [web:8080] generate new session id token 71ba2400357d14d4071439f277543114
2021-05-23 18:08:03.427  [7f0b2171a700] Debug: [web:8080] generate new authentication token ZmIyYTU5NjUtNmJmYS00Mzc0LWIxN2QtM2RkYzJmMmU2MTI1 for user
^[[I^[[O2021-05-23 18:08:43.981  [7f0b2171a700] Debug: web: Host:192.168.192.115 Uri;/json.htm?type=settings
2021-05-23 18:08:52.442  [7f0b21f3e700] Debug: [web:8080] cleaning sessions...
2021-05-23 18:08:52.444  [7f0b20f19700] Debug: [web:7443] cleaning sessions...

```

**Comment by gizmocuz** [comment]
Tested again, no database, added a dummy hardware and a dummy switch

https://192.168.0.3000/json.htm?type=devices&used=true&displayhidden=1 -> authorized , expected

Went to the settings, added a admin username/password. After pressing 'Apply' I needed to login (did not do this)

https://192.168.0.3000/json.htm?type=devices&used=true&displayhidden=1 -> authorized , **NOT expected** !? Hmmm

Now I do not have additional users in the system, I did previously ... 

After more debugging, I think I found the issue... but it's a bit complicated... There is a HTTP instance and a HTTPS instance.

Adding a Admin user via the HTTP interface caused the internal user-list of the HTTP instance to be updated, bit the HTTPS
(And visa versa)

Fixed now... took some time! (Aldo the patch seems simple *g*)

Thanks for reporting!

**Comment by kiddigital** [comment]
@gizmocuz Nice catch 👍
I was debugging also with @rwaaren but did not find that one yet.

Also learned now that http and https are 2 instances (of the same code) with each their own memory of users, passwords, etc.

Will rebase my JWT PR and also double check this scenario.

**Comment by rwaaren** [comment]
> Fixed now... took some time! (Aldo the patch seems simple _g_)


@gizmocuz, thx for spending time on this.

Unfortunately I still see the same behavior on my system.

Repeated the same steps  (started without database and added user/password in  Website protection. No logon with these new credentials + stop / start of domoticz)
```


./domoticz -sslwww 7443 -log domoticz.log -loglevel normal,status,error,debug -debuglevel normal,hardware,received,webserver,eventsystem,python,thread_id
2021-05-24 12:12:06.506  [7f60e9fac980] Status: Domoticz V2021.1 (build 13276) (c)2012-2021 GizMoCuz
2021-05-24 12:12:06.506  [7f60e9fac980] Status: Build Hash: 011e73010, Date: 2021-05-24 10:48:42
2021-05-24 12:12:06.506  [7f60e9fac980] Status: Startup Path: /home/pi/issue4833/
2021-05-24 12:12:06.514  [7f60e9fac980] Sunrise: 05:29:00 SunSet: 21:41:00
2021-05-24 12:12:06.514  [7f60e9fac980] Day length: 16:12:00 Sun at south: 13:35:00
2021-05-24 12:12:06.514  [7f60e9fac980] Civil twilight start: 04:43:00 Civil twilight end: 22:27:00
2021-05-24 12:12:06.514  [7f60e9fac980] Nautical twilight start: 03:37:00 Nautical twilight end: 23:33:00
2021-05-24 12:12:06.514  [7f60e9fac980] There is no astronomical twilight in the space of 24 hours
2021-05-24 12:12:06.551  [7f60e9fac980] Status: PluginSystem: Started, Python version '3.9.2'.
2021-05-24 12:12:06.553  [7f60e9fac980] Active notification Subsystems: (0/13)
2021-05-24 12:12:06.554  [7f60e9fac980] Status: WebServer(HTTP) started on address: :: with port 8080
2021-05-24 12:12:06.556  [7f60e9fac980] Status: WebServer(SSL) started on address: :: with port 7443
2021-05-24 12:12:06.557  [7f60e9fac980] Starting shared server on: :::6144
2021-05-24 12:12:06.557  [7f60e4c34700] Status: TCPServer: shared server started...
2021-05-24 12:12:06.558  [7f60df7fe700] Status: RxQueue: queue worker started...
2021-05-24 12:12:08.559  [7f60deffd700] Status: NotificationSystem: thread started...
2021-05-24 12:12:08.559  [7f60dffff700] Status: EventSystem: reset all events...
2021-05-24 12:12:08.560  [7f60dffff700] Status: EventSystem: reset all device statuses...
2021-05-24 12:12:08.593  [7f60dffff700] Status: Python EventSystem: Initializing event module.
2021-05-24 12:12:08.594  [7f60de7fc700] Status: EventSystem: Started
2021-05-24 12:12:08.594  [7f60ddffb700] Status: EventSystem: Queue thread started...

curl -v -i "http://192.168.192.115:8080/json.htm?type=settings" # attempt with http -->> access
*   Trying 192.168.192.115:8080...
* Connected to 192.168.192.115 (192.168.192.115) port 8080 (#0)
> GET /json.htm?type=settings HTTP/1.1
> Host: 192.168.192.115:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Length: 3440
Content-Length: 3440
< Cache-Control: no-cache
Cache-Control: no-cache
< Pragma: no-cache
Pragma: no-cache
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Content-Type: application/json;charset=UTF-8
Content-Type: application/json;charset=UTF-8
< Set-Cookie: DMZSID=2c48aee5a29d4eff4326456a86531707_ZDBiZmE0OWEtMjg5YS00OGQyLWJmYmYtZDJhZWI4ZWM3Njk2.1621851758; HttpOnly; path=/; Expires=Mon, 24 May 2021 10:22:38 GMT
Set-Cookie: DMZSID=2c48aee5a29d4eff4326456a86531707_ZDBiZmE0OWEtMjg5YS00OGQyLWJmYmYtZDJhZWI4ZWM3Njk2.1621851758; HttpOnly; path=/; Expires=Mon, 24 May 2021 10:22:38 GMT

<
{
        "AcceptNewHardware" : 1,
 ...
* Connection #0 to host 192.168.192.115 left intact


2021-05-24 12:12:38.456  [7f60e6c38700] Debug: web: Host:192.168.192.115 Uri;/json.htm?type=settings
2021-05-24 12:12:38.457  [7f60e6c38700] Status: Incoming connection from: 192.168.192.115
2021-05-24 12:12:38.457  [7f60e6c38700] Debug: [web:8080] generate new session id token 2c48aee5a29d4eff4326456a86531707
2021-05-24 12:12:38.457  [7f60e6c38700] Debug: [web:8080] generate new authentication token ZDBiZmE0OWEtMjg5YS00OGQyLWJmYmYtZDJhZWI4ZWM3Njk2
2021-05-24 12:13:06.554  [7f60e745c700] Debug: [web:8080] cleaning sessions...
2021-05-24 12:13:06.557  [7f60e6437700] Debug: [web:7443] cleaning sessions...


curl -v -k -i "https://192.168.192.115:7443/json.htm?type=settings" # first attempt with https -->> failed
*   Trying 192.168.192.115:7443...
* Connected to 192.168.192.115 (192.168.192.115) port 7443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure



curl -v -k -i "https://192.168.192.115:7443/json.htm?type=settings"  # 2nd attempt with https -->> access
*   Trying 192.168.192.115:7443...
* Connected to 192.168.192.115 (192.168.192.115) port 7443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=obscured
*  start date: Mar 10 13:41:52 2021 GMT
*  expire date: Jun  8 13:41:52 2021 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /json.htm?type=settings HTTP/1.1
> Host: 192.168.192.115:7443
> User-Agent: curl/7.74.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Length: 3440
Content-Length: 3440
< Cache-Control: no-cache
Cache-Control: no-cache
< Pragma: no-cache
Pragma: no-cache
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Content-Type: application/json;charset=UTF-8
Content-Type: application/json;charset=UTF-8
< Set-Cookie: DMZSID=10d849ce5510fb30f9f530106811aaa8_N2MzYTA5N2QtMWM0My00OTg4LWFjOTEtZGNmY2E0OTUxZDgz.1621851808; HttpOnly; path=/; Expires=Mon, 24 May 2021 10:23:28 GMT
Set-Cookie: DMZSID=10d849ce5510fb30f9f530106811aaa8_N2MzYTA5N2QtMWM0My00OTg4LWFjOTEtZGNmY2E0OTUxZDgz.1621851808; HttpOnly; path=/; Expires=Mon, 24 May 2021 10:23:28 GMT

<
{
        "AcceptNewHardware" : 1,
......

2021-05-24 12:13:28.242  [7f60e5c36700] Debug: web: Host:192.168.192.115 Uri;/json.htm?type=settings
2021-05-24 12:13:28.243  [7f60e5c36700] Status: Incoming connection from: 192.168.192.115
2021-05-24 12:13:28.243  [7f60e5c36700] Debug: [web:7443] generate new session id token 10d849ce5510fb30f9f530106811aaa8
2021-05-24 12:13:28.243  [7f60e5c36700] Debug: [web:7443] generate new authentication token N2MzYTA5N2QtMWM0My00OTg4LWFjOTEtZGNmY2E0OTUxZDgz
```

**Comment by gizmocuz** [comment]
Thats probably because of the cookie... you should see a setup->logout option

**Comment by rwaaren** [comment]
I see that and if I use that yhe log shows:

```
2021-05-24 12:41:47.652  [7f40dc476700] Debug: web: Host:192.168.192.118 Uri;/json.htm?type=command&param=dologout
2021-05-24 12:41:47.652  [7f40dc476700] Debug: Web: Logout : remove session 3aa0f0242781bf9996bf26aedcda8fc5
```

but even after stopping domoticz and ensuring UserSessions table is empty before restarting it I can access the API without user / password when using one of the below curls from the server.

```
curl -v -k -i "https://192.168.192.115:7443/json.htm?type=settings" 
curl -v  -i "http://192.168.192.115:8080/json.htm?type=settings" 
```

**Comment by gizmocuz** [comment]
It's much more easier to use your browser instead of those curl commands...

So after having set a web username and password you should be presented by a login screen correct?
At this point you should also get a unauthorized message if you want to query devices

http://192.168.192.115:8084/json.htm?type=devices&used=true&displayhidden=1

(I only tested with the devices call)

**Comment by gizmocuz** [comment]
Just tested, working now as expected. I assume this is caused by the cookie, just logout (from the Domoticz menu) and now you should not be able to request the settings of devices via the api

**Comment by rwaaren** [comment]
> Just tested, working now as expected. I assume this is caused by the cookie, just logout (from the Domoticz menu) and now you should not be able to request the settings of devices via the api


Sorry same result. 
And testing from the browser does not help here because the issue does not occur when accessing domoticz from another IP.
It only occurs when accessing from the domoticz server with the IP address of the first ethernet port.

127.0.0.1 , localhost, wlan address or from browser all works as expected.
192.168.192.115 (IP of first ethernet port of domoticz server) does not work as expected.

**Comment by gizmocuz** [comment]
@rwaaren , In that case there where two issues. One the difference in users for HTTP and HTTPS, and this issue.
But in the browser I use my IP address 192.168.x.x, not 127.0.0.1
I will do more testing

**Comment by kiddigital** [comment]
> @rwaaren , In that case there where two issues. One the difference in users for HTTP and HTTPS, and this issue.
> 
> But in the browser I use my IP address 192.168.x.x, not 127.0.0.1
> 
> I will do more testing

Did some testing with @rwaaren as well and think we found the problem. Now trying to figure out best way to solve it...

**Comment by rwaaren** [comment]
@kiddigital @gizmocuz,

I am sure below is not the best or even a good solution but it does solve the issue.

In cWebem.cpp

```

		bool IsIPInRange(const std::string &ip, const _tIPNetwork &ipnetwork)
		{
			bool bIsIPv6 = (ip.find(':') != std::string::npos);
			if (ipnetwork.bIsIPv6 != bIsIPv6)
				return false;

			uint8_t IP[16] = { 0 };
			if (inet_pton((!bIsIPv6) ? AF_INET : AF_INET6, ip.c_str(), &IP) != 1)
				return true;

			int iASize = (!bIsIPv6) ? 4 : 16;
			for (int ii = 0; ii < iASize; ii++)
				if (ipnetwork.Network[ii] != (IP[ii] & ipnetwork.Mask[ii]))
					return false;
	
			std::string allowedNetworks;
			int rnvalue;
			m_sql.GetPreferencesVar("WebLocalNetworks", rnvalue, allowedNetworks);
			if ( allowedNetworks.empty() )
			{
				_log.Log(LOG_ERROR, "cWebem: local netWork not open!");
				return false;
			}
			return true;
		}
```

**Comment by kiddigital** [comment]
@rwaaren indeed not a good/the best solution 😁 but the check performed here is done elsewhere as well but 'fails' because the local network based on the hostname is always added so the list is not empty (while here when just looking at the db settings it is).

(And bad idea to perform this db query as it gets executed for each request to the webserver, but that is a different thing to resolve 😉)

When I have some time this evening or tomorrow, I will create a nicer fix (I hope).

**Comment by gizmocuz** [comment]
Yes this is a extreme expensive solution...

**Comment by rwaaren** [comment]
@gizmocuz, 

please check #4824 where the last commits solved the issue without using the expensive database call.

**Comment by gizmocuz** [comment]
This needs to be solved correctly if there is still a issue.

I'm currently a bit occupied, but I will recheck this problem again.
The issue between http/https is already solved.

There should be no difference between any adapter when using 0.0.0.0 as listen address.
When you listen to a specific adapter , it should not be possible to even reach Domoticz from another adapter/subnet

PR 4824 is something completely else and can not be used as a patch for this issue
