### ISSUE TITLE
Latest Dev Domoticz crash when starting zigbee2mqtt plugin

### ISSUE THREAD

**Issue by lwalbert** [domoticz/domoticz#4861]
Latest implementation "Extended plugin framework initial version" https://github.com/domoticz/domoticz/commit/789f5e76a seems to crash domoticz when starting zigbee2mqtt plugin.

```
`2021-06-14 17:14:03.952  [713ff220] Status: EventSystem: reset all device statuses...
2021-06-14 17:14:04.222  [74a86220] Status: PluginSystem: 1 plugins started.
2021-06-14 17:14:04.621  [6c3fb220] Status: Zigbee: (Zigbee) Initialized version 3.0.1
Fatal Python error: Segmentation fault

Current thread 0x6c3fb220 (most recent call first):
2021-06-14 17:14:04.624  [6c3fb220] Error: Domoticz(pid:25830, tid:25852('Zigbee')) received fatal signal 11 (Segmentation fault)
2021-06-14 17:14:04.624  [6c3fb220] Error: siginfo address=0x64e6, address=(nil)
2021-06-14 17:14:04.646  [6c3fb220] Error: Failed to start gdb, will use backtrace() for printing stack frame

2021-06-14 17:14:04.647  [6c3fb220] Error: #0  ./domoticz() [0x237f14]
2021-06-14 17:14:04.648  [6c3fb220] Error: #1  ./domoticz : signal_handler(int, siginfo_t*, void*) + 0x1f8 [0x2388d0]
2021-06-14 17:14:04.648  [6c3fb220] Error: #2  /lib/arm-linux-gnueabihf/libc.so.6 : __default_rt_sa_restorer + 0 [0x76919130]
Segmentation fault
`
```
Domoticz V2021.1 (build 13322)
Build Hash: 789f5e76a
Python version '3.7.3'.

And domoticz_crash.log file is empty.

br
lwalbert

**Comment by waltervl** [comment]
Should perhaps be fixed with https://github.com/domoticz/domoticz/commit/5e673c1272e9f9af9fdf7c5e58d952c8ae4c0e87
Please retry latest beta

**Comment by lwalbert** [comment]
Hi @waltervl 
Retested with latest beta.
Still same issue.


```
2021-06-16 13:23:11.018  [713ff220] Status: EventSystem: reset all device statuses...
2021-06-16 13:23:11.388  [749fc220] Status: PluginSystem: 1 plugins started.
2021-06-16 13:23:12.012  [6d3fd220] Status: Homekit: MQTT: Connecting to 10.0.0.20:1883
2021-06-16 13:23:12.395  [6d3fd220] Status: Homekit: MQTT: connected to: 10.0.0.20:1883
2021-06-16 13:23:12.596  [6d3fd220] Status: Homekit: MQTT: Subscribed
2021-06-16 13:23:12.824  [6c3fb220] Status: Zigbee: (Zigbee) Initialized version 3.0.1
Fatal Python error: Segmentation fault

Current thread 0x6c3fb220 (most recent call first):
2021-06-16 13:23:12.826  [6c3fb220] Error: Domoticz(pid:25895, tid:25917('Zigbee')) received fatal signal 11 (Segmentat                                   ion fault)
2021-06-16 13:23:12.827  [6c3fb220] Error: siginfo address=0x6527, address=(nil)
2021-06-16 13:23:12.849  [6c3fb220] Error: Failed to start gdb, will use backtrace() for printing stack frame

2021-06-16 13:23:12.851  [6c3fb220] Error: #0  ./domoticz() [0x238274]
2021-06-16 13:23:12.851  [6c3fb220] Error: #1  ./domoticz : signal_handler(int, siginfo_t*, void*) + 0x1f8 [0x238c30]
2021-06-16 13:23:12.851  [6c3fb220] Error: #2  /lib/arm-linux-gnueabihf/libc.so.6 : __default_rt_sa_restorer + 0 [0x768                                   8f130]
Segmentation fault
```

**Comment by dobber81** [comment]
I get Fatal Segmentation fault for another plugin (UPS Monitor) on latest beta. Build 13314 is latest ok build for me. Crash and burn with 13329.

**Comment by salopette** [comment]
Pi 3- Debian Buster 10
Version: 2021.1 (build 13329)
Build Hash: 24521c255
Compile Date: 2021-06-16 08:55:35
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

Uptime: 2 Minuten, 45 Sekunden

I also crash domoticz.
If I deactivate plugins (Shelly, Z2M, Tasmota, WLED, ect ..) then I can start domoticz.

**Comment by waltervl** [comment]
@dnpwwo Did you see this?

**Comment by vernwood** [comment]
Here also. after update to build 13329 domoticz crashed.
after disable most of the hardware i can start domoticz again.

**Comment by mikewoudenberg** [comment]
Same here. Had to disable Shelly-Mqtt and zigbee-mqtt plugins. This whole situation did give me a nice excuse to hook up backup physical switches to my sunscreens though :)

**Comment by EdwinKort** [comment]
How do you disable the plugins if you can't access Domoticz? Removing them from the server?

**Comment by dobber81** [comment]
> How do you disable the plugins if you can't access Domoticz? Removing them from the server?

Domoticz is available for maybe 30 seconds before crashing.

**Comment by waltervl** [comment]
For beta's there is now an automatic backup created in domoticz/backups for easy restore!

**Comment by mikewoudenberg** [comment]
You can disable the plugin via the cli when domoticz is not running as described under the hardware section of the troubleshooting guide https://www.domoticz.com/wiki/Troubleshooting

**Comment by EdwinKort** [comment]
> For beta's there is now an automatic backup created in domoticz/backups for easy restore!

Unfortunately..

: cd: backup: 
No such file or directory:

**Comment by waltervl** [comment]
> > For beta's there is now an automatic backup created in domoticz/backups for easy restore!
> 
> Unfortunately..
> 
> : cd: backup:
> No such file or directory:

cd backups

**Comment by mojso** [comment]
after update to build 13329 domoticz crashed

**Comment by JanJaapKo** [comment]
Hi, same issue here. Found the backups (permission only set to root....). Is there an instruction on how to restore this backup? Or better yet: does Domoticz provide a script to do so?

And would it be possible to remove the rollout of this version?

**Comment by waltervl** [comment]
There is no script to restore.
Easiest option will be to rename the current domoticz folder to domoticz.old and extract the backup instead.

**Comment by JanJaapKo** [comment]
last backup of today led to same error. Decided to roll back to release on current status of database

**Comment by marstum** [comment]
> There is no script to restore.
> Easiest option will be to rename the current domoticz folder to domoticz.old and extract the backup instead.

Thanks for the hint, going back to the previous version with the backup prior to upgrade was working well.

**Comment by dnpwwo** [comment]
Looks like I accidentally used a Python 3.9 function, I'll push a fix today

**Comment by mealgi** [comment]
Hello 
I have the same issue with Domoticz V2021.1 (build 13329) running on a RPI3+ / Buster
Build Hash: 24521c255-modified, Date: 2021-06-16 08:55:35

I created a blank 2021.1 domoticz application with only one Hardware based on disc_usage PI plugin from https://github.com/Xorfor/Domoticz-Disc-usage-Plugin. See https://www.domoticz.com/wiki/Plugins.

2021-06-17 13:18:32.405 System-Disk Usage Root hardware started.
2021-06-17 13:18:32.404 Status: System-Disk Usage Root: (System-Disk Usage Root) Entering work loop.
2021-06-17 13:18:32.405 Status: System-Disk Usage Root: (System-Disk Usage Root) Started.
2021-06-17 13:18:32.405 Status: NotificationSystem: thread started...
2021-06-17 13:18:32.406 Status: EventSystem: reset all events...
2021-06-17 13:18:32.413 Status: EventSystem: reset all device statuses...
2021-06-17 13:18:32.576 Status: Python EventSystem: Initializing event module.
2021-06-17 13:18:32.577 Status: EventSystem: Started
2021-06-17 13:18:32.577 Status: EventSystem: Queue thread started...
2021-06-17 13:18:32.754 Status: PluginSystem: 1 plugins started.
2021-06-17 13:18:32.770 Status: System-Disk Usage Root: (System-Disk Usage Root) Initialized version 1.2.0, author 'Xorfor'
2021-06-17 13:18:32.782 Error: Domoticz(pid:823, tid:846('System-Disk Usa')) received fatal signal 11 (Segmentation fault)
2021-06-17 13:18:32.782 Error: siginfo address=0x337, address=(nil)

in Domoticz_crash. log it shows:
Thread 19 (Thread 0x6deff210 (LWP 14350)):
#0  __waitpid (options=0, stat_loc=0x6defdf20, pid=14353) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  __waitpid (pid=14353, stat_loc=0x6defdf20, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
#2  0x00280814 in dumpstack_gdb(bool) ()
#3  0x00280de0 in signal_handler(int, siginfo_t*, void*) ()
#4  <signal handler called>
#5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
#6  <signal handler called>
#7  0x00000000 in ?? ()
#8  0x0062d7f8 in Plugins::CPlugin::Start() ()
#9  0x006376fc in Plugins::onStartCallback::ProcessLocked() ()
#10 0x0020d030 in Plugins::CPluginMessageBase::Process() ()
#11 0x00635748 in Plugins::CPlugin::Do_Work() ()
#12 0x0089d9b4 in execute_native_thread_routine ()
#13 0x76a94494 in start_thread (arg=0x6deff210) at pthread_create.c:486
#14 0x76928578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

BR

**Comment by dnpwwo** [comment]
Fix has been pushed

**Comment by lwalbert** [comment]
Great job,
Tested with latest fix, python plugins works again.
build: 13330

Thanks

**Comment by pipiche38** [comment]
works ! thanks ( build 13330)

**Comment by waltervl** [comment]
I see some reports on the forum that it still does not work
https://www.domoticz.com/forum/viewtopic.php?f=6&t=36494
https://www.domoticz.com/forum/viewtopic.php?f=6&t=36516

**Comment by JanJaapKo** [comment]
Neither of these reports indicate whoich versions they are using.At this moment, I'm still getting offered to go to 13329 (at least on the Domoticz front end GUI) which does not contain your bug fix. So perhaps the guys on the forum did not get your 13330 version yet.

**Comment by RomanSladecek** [comment]
when we can expect 13330 beta release and upgradable that through GUI pls?  (for Raspberry PI)

**Comment by RomanSladecek** [comment]
13330 beta was released, and it fixed those problems :) thanks
