### ISSUE TITLE
Offset not applied to exported data

### ISSUE THREAD

**Issue by Enggmaug** [domoticz/domoticz#5540]
Hello,

I run Domoticz Version: 2022.2 on a RPi 3.
I interface with Xiaomi Temp sensors, and forward their values to an influxdb dB to display in Grafana.

The issue I see is that when a temperature offset is applied on a sensor, through the Modification tab at the bottom of the sensor display area, it does not affect the data sent to Influxdb, but only the domoticz displayed temp.

Regards,
Guillaume.

**Comment by gizmocuz** [comment]
I don't understand your problem 100%, but when you edit a temperature device and specify a adjustment, then from this moment, the adjustment is performed on the incoming data
Also from that moment it is pushed to Influx.
So the value that is displayed is also pushed

**Comment by waltervl** [comment]
@Enggmaug is your temp sensor controlled by a python plugin? If yes what plugin? Could be related to this: https://github.com/domoticz/domoticz/issues/2881 (and others like https://github.com/domoticz/domoticz/pull/2899).
But perhaps solved in the new DomoticzEx python framework?

**Comment by Enggmaug** [comment]
Hello, 

No Python plugin, I believe... I forgot to say I have a Zigate. The Zigate plugin provides the temp sensor values. Then in domoticz, I apply an adjustment that I can't see in the Grafana interface.
I still see the temp value without adjustment.

Maybe the issue needs to be opened on Zigate plugin side. I would not believe so, but I don't know for certain.

**Comment by waltervl** [comment]
Zigate plugin is a python plugin. So this is the same issue probably. @pipiche38 is there still an issue with temperature adjustment and python plugins?

**Comment by gizmocuz** [comment]
The reason is that these python plugins are modifying the database directly and do not follow the normal reception protocols.
It's not only related to the zigate python plugin

Luckily the zigate is also supported in Zigbee2MQTT
