### ISSUE TITLE
Memory leakage in Domoticz

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#6030]
Using:  Version: 2024.3 (build 15882)
Build Hash: 0eadb5539
Compile Date: 2024-01-29 11:58:42
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 11 2023, 09:51:27) [GCC 8.3.0
After this https://github.com/domoticz/domoticz/issues/5984 memory leakage was solved there is still an unexplained leakage present.
![15 02 2024_09 45 55_REC](https://github.com/domoticz/domoticz/assets/24824113/e60a8ae0-a73d-48e8-ab2b-78b5a567db0e)
On this graph you can see that on 3 febr. I restarted Domoticz (B.t.w. and the Raspberry) which initially started with some 70Mb.
It settled the days after to around 130Mb and stayed there. For no reason I could discover at 9 febr. it raised to 210 Mb and settled again. The 13 febr. it started rising again, now at 350 Mb and it is still rising. I used gdb again to investigate some parts of the not released memory again. It to big to look over and investigate all > 200Mb
I found that some part are only filled with 0x00 (zero;'s) and some parts are filled with multiple loglines of only a small part of the logging (less then 1 second). But every logline is repeated more then 20-30 times. And I found a lot of parts of my dzVents scripts in some parts of the memory. I know this will be a tough one to discovered where it goes wrong. You can see from the graph that Domoticz used to be very stable in Process Memory.
I wonder if others experience the same phenomena?
And if someone found the cause.

**Comment by pipiche38** [comment]
You might want to test it with 2024.4 ;-)Envoyé de mon iPhoneLe 15 févr. 2024 à 10:04, SargonofAssyria ***@***.***> a écrit :﻿
Using:  Version: 2024.3 (build 15882)
Build Hash: 0eadb55
Compile Date: 2024-01-29 11:58:42
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 11 2023, 09:51:27) [GCC 8.3.0
After this https://github.com//issues/5984 memory leakage was solved there is still an unexplained leakage present.
15.02.2024_09.45.55_REC.png (view on web)
On this graph you can see that on 3 febr. I restarted Domoticz (B.t.w. and the Raspberry) which initially started with some 70Mb.
It settled the days after to around 130Mb and stayed there. For no reason I could discover at 9 febr. it raised to 210 Mb and settled again. The 13 febr. it started rising again, now at 350 Mb and it is still rising. I used gdb again to investigate some parts of the not released memory again. It to big to look over and investigate all > 200Mb
I found that some part are only filled with 0x00 (zero;'s) and some parts are filled with multiple loglines of only a small part of the logging (less then 1 second). But every logline is repeated more then 20-30 times. And I found a lot of parts of my dzVents scripts in some parts of the memory. I know this will be a tough one to discovered where it goes wrong. You can see from the graph that Domoticz used to be very stable in Process Memory.
I wonder if others experience the same phenomena?
And if someone found the cause.

**Comment by SargonofAssyria** [comment]
I updated to 15910, so let's wait and see.

**Comment by SargonofAssyria** [comment]
Now a few days later the BIG leakage is gone, but there still remains a small leakage present.
Will try to investigate what the origine is.

**Comment by SargonofAssyria** [comment]
After more then 10 days that Domoticz is up, I found that the leakage is about 2.5 Mb in those 10 days.
So significant small to the total memory usage.
I can not pinpoint the exact case of the leakage, it might have to do with certificates (Root CA) and/or dzVents.
But which of the cause I cannot find.
So I close this issue until I find something real.

**Comment by SargonofAssyria** [comment]
I found this error. Could that have any impact on memory leakage?
```
2024-03-08 07:26:23.983 Error: dzVents: Error in ProcessNotificationItem: in Json::Value::resolveReference(key, end): requires objectValue
2024-03-08 07:26:23.983 Error: Lua table notification is not published. Not all sub tables are closed!
```

**Comment by SargonofAssyria** [comment]
Unfortunately after a little bit more then 3 weeks Domoticz became unresponsive for a few minutes that Monit has to restart Domoticz. But until then the memory usage of Domoticz did grow slowly to over 144 Mb just before the restart.

**Comment by Vlietland** [comment]
Some time ago I have posted a memory leak issue on the forum: https://www.domoticz.com/forum/viewtopic.php?p=315233&hilit=memory+leak#p315233

In my case the issue is related to the amount of enabled hardware. The more hardware I enable, thus the more devices are enabled, the more mem leaks away. There seems no relationship with the type of hardware, it seems simply related to the number of devices. Could it be related to data logging?

**Comment by gizmocuz** [comment]
Sure.... But it should not need an increasing memory issue

**Comment by Vlietland** [comment]
Can I perform some sort of testing to provide more debugging information? What I did sofar is:
- Disable scripting
- Disable hardware

**Comment by pipiche38** [comment]
What type of Hardware plugin are you referring ? If these are Python plugin, I do confirm that there is a memory leak every time you restart a Python plugin.
I'm not sure anything can be done here as this is probably deep into the framework itself

**Comment by Vlietland** [comment]
Below the hardware types I am referring to. If I disable all hardware there are no memory leaks. As soon as I start enabling hardware the built up of memory occurs. Most leakage occurs with enabling MQTT since that enables approx 700 sensors (=domoticz devices).
![image](https://github.com/domoticz/domoticz/assets/47453952/c0c71dec-d4f3-423c-acae-6dfe30cb5151)

**Comment by Vlietland** [comment]
herewith the memory builtup: 
![image](https://github.com/domoticz/domoticz/assets/47453952/20fe7014-70f1-48b1-bfc0-4b1e901d00f5)

It is solely caused by the Domoticz process(es). 
As workaround I use a cronjob to release the mem, otherwise the OOM-killer does it for me:
'30 3 *  *  *    root    service domoticz.sh restart'

ps: the release today at 11:45 was caused by updating the latest beta.

**Comment by SargonofAssyria** [comment]
I saw your post on the forum. What is the output of
```
sudo ps aux | grep domoticz | grep -v grep
```
Because I see you have a lot of PID's

**Comment by Vlietland** [comment]
Hi the output is:
22634 21.8 18.6 769888 357848 ?       Ssl  03:30 225:45 
/home/admin/domoticz/domoticz -daemon -www 80 -sslwww 443

reply to:
>
> I saw your post on the forum. What is the output of
> sudo ps aux | grep domoticz | grep -v grep
>
> Because I see you have a lot of PID's

**Comment by SargonofAssyria** [comment]
Sorry about the question. I saw later that those PID's were from threads. That's why I deleted the post.
I have about 22 Hardware active. I see an increase in leakages, but not as much as you.
With the help of pmap I see that the memory leakage, but still can not figure out where it comes from.

**Comment by SargonofAssyria** [comment]
Yesterday, out of the blue, Process Memory rapidly raised to over 140Mb (my alarm limit) and I rebooted the Raspberry.
![23 03 2024_11 40 41_REC](https://github.com/domoticz/domoticz/assets/24824113/8b2d4aee-1bb7-42c7-a3b8-2a9eb30b632a)
Still I did not found the reason.

**Comment by pipiche38** [comment]
Do you have automatic backup ? I found that usually this is taking some memory, but the next time it won't.

**Comment by SargonofAssyria** [comment]
I have several backups, dzVents and external scripts by cron. Those are not the initiators.
The sudden rise starts between 15:30 and 15:35
I look in the domoticz.log, but nothing special happened during that period.
I looked is syslog, messages, cron.log and others, but nothing special.
I looked at CPU_Usage, RPi Memory Usage, but nothing that happened during or around that period.
B.t.w. the drop of "Process Usage" at 21:00 hours is from the reboot of the Raspberry Pi 4B, because I was alarmed that the Process Usage came above 140Mb

**Comment by Vlietland** [comment]
I have disabled auto backup a few days ago. Also for my setup it makes no difference: 
![image](https://github.com/domoticz/domoticz/assets/47453952/28954950-a347-47d2-bbbb-42a4c47329f6)

I'm curious about the little dips in the mem usage. Might it be a starting point of finding the root-cause of the leak? It corresponds with the mem usage of Domoticz.

**Comment by SargonofAssyria** [comment]
You better make pictures and conclusions with the "Process Usage" widget, because that is only about Domoticz.
Memory Usage is about the whole Raspberry Pi Memory. Those little dips might be Linux garbage collection.

**Comment by Vlietland** [comment]
Ah right, was not aware of that widget. Indeed the little dips are not present here: 
![image](https://github.com/domoticz/domoticz/assets/47453952/2c24ab0f-9b7c-481c-b0af-0737c5fc5a50)

**Comment by SargonofAssyria** [comment]
The story continues. After I updated Domoticz to version 15910 I ran Domoticz continuously for over 4 weeks from mid April until 19 May On the picture you can see that the increase in memory took place over the whole period. 19 May I upgraded to version 15992. There was a normal memory increase as you can expect in the beginning after the start.
Today around 11:00 the increase in memory consumption rose for no reason unexpected from 120 Mb to currently 210 Mb.
Domoticz is still working as it should with no errors. I will let it run until it get unresponsive or crashes.
I looked with pmap for the memory consumption. The only thing I notice is that the chuncks that are not released are 8192 Mb in size.
![21 05 2024_18 31 44_REC](https://github.com/domoticz/domoticz/assets/24824113/121fe137-7887-4a89-ba52-5dd35cf1675a)

**Comment by SargonofAssyria** [comment]
The Process Memory keep growing in the same pace, and it at the moment over 400 Mb. Domoticz is still running fine.
I made a Domoticz Process coredump, which is over 750 Mb.
I try to look over that dump and see if I find anything unusual, but 750 Mb is big, so I doubt if I will find anything.

**Comment by SargonofAssyria** [comment]
Did not find anything yet. At 500 Mb I had to reboot my Raspberry Pi 4. Will see what happens.

**Comment by pipiche38** [comment]
do you use OpenWeatherMap ? I wonder if there is not something in it, as this is the only plugin I enabled since a while and more-less since them I'm getting leakage that I didn't have before

**Comment by SargonofAssyria** [comment]
I use the OpenWeatherMap as Hardware, not as plugin.
But in my case it is strange that for 4 weeks the Memory Leakage is small but consistant, but suddenly it rose much more.

**Comment by pipiche38** [comment]
Sorry I mean Hardware

**Comment by SargonofAssyria** [comment]
Today I noticed this:
![21 06 2024_06 21 20_REC](https://github.com/domoticz/domoticz/assets/24824113/84fb7530-9a5c-4434-bc24-c7cb05681c48)
I updated Domoticz twice because of the new Energy Dashboard.
In the first part from 18 June I had an unnoticed dzVents error every minute.
At the second update late 19 June I discovered the dzVents error and corrected it.
The slope of the memory increase is different, but it might be normal.

The second thing I noticed is the following.
I previous had the Ziggo email problem that was corrected, but I still was left with a Ziggo error when I wanted to attach a picture to the email. If lived with that for a long time, because I got my attachment via Telegram. Recently I changed the email server, so my problem was solved, and it looks like that (part) of the memory leakage was solved.
I looked into the source, and I am not an expert on C++ coding, but I wondered if this was not a memory leak.
From smtpclient/SMTPClient.cpp
```
        smtp_ctx.pDataBytes = new char[rmessage.size()];
        if (smtp_ctx.pDataBytes == nullptr)
        {
            _log.Log(LOG_ERROR, "SMTP Mailer: Out of Memory!");

            curl_easy_cleanup(curl);
            curl_slist_free_all(slist1);
            return false;
        }
        smtp_ctx.sDataLength = rmessage.size();
        memcpy(smtp_ctx.pDataBytes, rmessage.c_str(), smtp_ctx.sDataLength);

        curl_easy_setopt(curl, CURLOPT_READFUNCTION, smtp_payload_reader);
        curl_easy_setopt(curl, CURLOPT_READDATA, &smtp_ctx);

        /* provide a buffer to store errors in */
        curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, errbuf);

        /* set the error buffer as empty before performing a request */
        errbuf[0] = 0;

        ret = curl_easy_perform(curl);

        curl_easy_cleanup(curl);
        curl_slist_free_all(slist1);
        delete[] smtp_ctx.pDataBytes;

        if (ret != CURLE_OK)
        {
            _log.Log(LOG_ERROR, "SMTP Mailer: Error sending Email to: %s !", m_Recipients[0].c_str());
            size_t len = strlen(errbuf);
            _log.Log(LOG_ERROR, "libcurl: (%d) ", ret);
            if(len)
                _log.Log(LOG_ERROR, "%s%s", errbuf, ((errbuf[len - 1] != '\n') ? "\n" : ""));
            else
                _log.Log(LOG_ERROR, "%s\n", curl_easy_strerror(ret));
            return false;
        }
    }
    catch (...)
    {
        _log.Log(LOG_ERROR, "SMTP Mailer: Error sending Email to: %s !", m_Recipients[0].c_str());
        return false;
    }
    return true;

```
In the logging I cannot distinguish between the normal error log and the catch.
But I wonder should not there be a "delete[] smtp_ctx.pDataBytes;" in the catch too?

**Comment by gizmocuz** [comment]
I'm afraid that's not it... There can't be a crash after the allocation.  all these curl calls are not giving an exception

I still made a commit for this, but I am 100% sure that memory is not allocated when there is a crash here

**Comment by SargonofAssyria** [comment]
Could you also make a little change (in text) so that I can see if it is the normal error logging or the catch?
Now they are exactly the same.

**Comment by gizmocuz** [comment]
Done!

**Comment by SargonofAssyria** [comment]
Tnx, will switch back to Ziggo with email with the attachment. Will see if it was an 'normal' error or the catch.
Will come back on this.

**Comment by SargonofAssyria** [comment]
Tested it intensely, and you are right. The error in the email is NOT coming from the catch, it's a normal error.
I could not find that those email errors are responsible for the memory leakage.
So my "quest" continues, because the memory leakage is still there.

**Comment by SargonofAssyria** [comment]
I am still working on this issue, because I still have a small growth over time on the memory consuption.
I sometimes have this error.
```
2024-09-09 19:19:04.939 Error: dzVents: Error in ProcessNotificationItem: in Json::Value::resolveReference(key, end): requires objectValue
2024-09-09 19:19:04.939 Error: Lua table notification is not published. Not all sub tables are closed!
```
Can't find in the Domoticz.log file to which dzVents script it is related to, but the text **Not all sub tables are closed!**
Hits possible to a memory leak???

**Comment by SargonofAssyria** [comment]
Today I accedently found my dzVents script with which I can create the memory leakage.
It looks like lua tables in dzVents create the problem.
I have to do some more testing and come back here in a few weeks.

**Comment by SargonofAssyria** [comment]
A few days ago I rewrote that dzVents script to not use lua tables any more.
The leakage is gone for that script.
Now I have to go over all of my dzVents script to see if there are other uses for lua tables and if that could create leakage also.
The found script had a table of approx. 100Kb, quite big. I don't know why I did that but it made the memory leakage obviuous.

**Comment by gizmocuz** [comment]
Can you provide a simple example using the tables that create the leak?

**Comment by SargonofAssyria** [comment]
Enclosed my first script to check on zigbee devices lastupdate. It was quick and dirty, getting the total database in an array and then process it. But it brought the problem in view. I already rewrote the script to not use an array any more, and memory leakage is gone, at least  this big one. The memory leakage is present when there is a device with lastupdate of more the 1440 minutes. Then it looks like the array is not nill anymore.

[check zigbee lastupdate.txt](https://github.com/user-attachments/files/20033950/check.zigbee.lastupdate.txt)

**Comment by gizmocuz** [comment]
So, the only time you use anything from Domoticz is in this code block


```
					dz.devices().forEach(function(device)
						a, b = string.find(device.deviceId, x.ieeeAddr)
						if a ~= nil then
							message = message .. 'Device ' .. device.name .. 
								' seems to be dead for more then '.. tostring(treshold) .. ' minutes.\r\n'
						end
					end)
```

You are building a large message, and later call the dz.log and dz.notify

When you do not build the message (remark that line), just add a quick log message above the forEach, is the memory leak issue present?
If not, and you build the message, but do not call dz.log/dz.notify, is the memory leak present?

**Comment by SargonofAssyria** [comment]
When there is NO device over the 1440 limit then that code block is not executed and NO memoryleak.
When there is a device over the limit and that code block is called and memoryleak is present.
I checked with a 1 minute interval and the memory consumption rises instandly and it looks by the amount of the array.
I am currently on holliday and cannot afford to test the running system, because if anything goes wrong I have a home that is not functional (automated).
But if you have zigbee you could test by a 1 minute limit instead of the 1440.
I am returning from holliday beginning of june, then I could test.
