### ISSUE TITLE
Netatmo connection failing since yesterday in last beta

### ISSUE THREAD

**Issue by lfzoz** [domoticz/domoticz#6280]
A few days ago netatmo failed to work, after forum advise I upgraded the domoticz to latest beta and used the new  authentication in the hardware domoticz page. All seems ok till yesterday where domoticz wanted to be upgraded to version  16581. Since then it's not working again -  all tries (remove and add, reauthenticate) ends with the same error " Error: Netatmo: Invalid/no data received (refresh tokens)... HTTP/2 403 " and the yellow message in the hardware page: tokens are invalid or expired. 
It seems more people face the same issue: 
[forum](https://forum.domoticz.com/viewtopic.php?p=324497)

**Comment by JurgenLB** [comment]
Stop and start domoticz from command line
`2025-03-20 19:48:07.630  Status: Netatmo: Use refresh token from database...`
`2025-03-20 19:48:07.925  Error: Netatmo: Invalid/no data received (refresh tokens)... HTTP/2 403 `

`2025-03-20 19:59:37.863  Error: Netatmo: Invalid/no data received (refresh tokens)... HTTP/2 403`

`2025-03-20 20:08:51.030  Status: Netatmo: Status 1`

so in between I have manually stoped the Domoticz service and only after 10 min

I started Domoticz with failed the second time.

Then I stop Domoticz Service and waited 10 more minutes.

This gives a positive result as the Netatmo-system is accepting the login.

a quick fix can be a timer that blocks the login procedure 
But to change the authentication is more work.

**Comment by JurgenLB** [comment]
Did you see / Follow these 6 screens ?

![Image](https://github.com/user-attachments/assets/06590a2a-6f01-4763-b6a1-1b14d14caaf5)

![Image](https://github.com/user-attachments/assets/81825461-3e6c-4e81-b080-2583f3e8caa8)

![Image](https://github.com/user-attachments/assets/d52101b5-f33a-4ba9-aa24-682f94f2d466)

![Image](https://github.com/user-attachments/assets/9ee4ca4a-7da9-42d6-afcd-97abf791ea9a)

![Image](https://github.com/user-attachments/assets/1b44af76-4fb4-43b0-aa55-d2c1349e1499)

![Image](https://github.com/user-attachments/assets/265da7af-9013-4215-a86e-d53cdf77deb9)

**Comment by waltervl** [comment]
@JurgenLB Can you write down the complete install and authentication instruction fur current beta with screenshots in this topic? Then I can update the wiki https://wiki.domoticz.com/Netatmo accordingly. I think people are having difficulty to get the right instructions now as thing have changed compared to 2024.7

**Comment by JurgenLB** [comment]
I did a rewrite off the wiki for Netatmo and GizMoCuz has merged this.
But maybe you can add the 6 picture's I posted here to make it more clear.

Netatmo has a complex authentication system.

To sum it up;

### New Installation;
Log in by dev.netatmo.com
On dev.netatmo.com you create a App and press save 2 times.
This gives you the clientid and clientsecret 

On the Hardware page from Domoticz;
you select HardwareType 'Netatmo'
Fill in a Name
Fill in Clientid and clientsecret
Select the correct scope(s) for your devices
Press Button Login.
You can Login to Netatmo with E-mail and Password. (If you are already Login in you get directly to The accept page.
You see a configuration screen from Netatmo.
Then the Accept Page is displayed, You scroll to the bottom.
And press Accept.
This closes the window and when everything is correct the plugin works.

You get a message that nothing is selected so NEW HARDWARE is created.


### With a existing installation;
On the Hardware page from Domoticz;
you select the Hardware Line
Fill in Clientid and clientsecret
Select the correct scope(s) for your devices
Press Button Login.
You can Login to Netatmo with E-mail and Password. (If you are already Login in you get directly to The accept page.
You see a configuration screen from Netatmo.
Then the Accept Page is displayed, You scroll to the bottom.
And press Accept.
This closes the window and when everything is correct the plugin works.

When you want to disable the plugin
you select the Hardware Line on the Hardware page from Domoticz
switch the Enable button to Red and press update

When you want to enable the plugin
you select the Hardware Line on the Hardware page from Domoticz
switch the Enable button to Green and press update

The Add button is not in use anymore but still visible, this is different as normal expected for Domoticz.

### Problem situation
When you restart Domoticz or enable the plugin to close to the authentication then Netatmo Blocks the request,
and keeps blocking as long as there are continuous requests.

When I manually stop the system and wait 20 min then the Block is lifted and the authentication is OK

There is a access token and refresh token

**Comment by JurgenLB** [comment]
@waltervl after rereading the wiki.
there is 1 line incorrect.
`Then your Hardware is added or you can press 'ADD'.`
the 'or you can press ADD' part is incorrect to my understanding.

**Comment by zigbeefordomoticz** [comment]
Is that correct, that every time you login it creates a new plugin instances ?

**Comment by JurgenLB** [comment]
> Is that correct, that every time you login it creates a new plugin instances ?

No that is not Correct.

When there is no Hardware-line Selected then it makes a new Hardware-Instance

When you have a Hardware-line selected then it updates that Hardware.

**Comment by JurgenLB** [comment]
Today I notice when you have the hardware page opened for a longer time,
the buttons work but there is a Error Updating Hardware.

![Image](https://github.com/user-attachments/assets/942d47f8-6dc6-4af1-b256-8c23fec0ca95)

So When people see this message the login for Domoticz is not valid anymore, this is not a error from the plugin.

This is Off-topic;
I was expecting Domoticz to return to its login screen, but this is not the case. When I click on the Menu there is a redirect to the login page for Domoticz

![Image](https://github.com/user-attachments/assets/de3b667c-051c-4b24-97e1-d5c7b4c04502)

**Comment by waltervl** [comment]
@JurgenLB I updated the wiki page.

**Comment by lfzoz** [comment]
In the latest beta 16583 it seems to work. Although it shows an error about scope rights, that is not very clear. I have an internal station and allowed access of the app to Home Couch. Data seems to be read.

 2025-03-22 18:14:40.503 Status: Netatmo: Home Status Details, size (number of homes) is 0
2025-03-22 18:14:40.503 Status: Netatmo: Status 1
2025-03-22 18:16:40.168 Status: Netatmo: Worker stopped...
2025-03-22 18:16:58.942 Status: Netatmo: Worker started...
2025-03-22 18:17:03.945 Status: Netatmo: Use refresh token from database...
2025-03-22 18:17:03.946 Status: Netatmo: Requesting refreshed tokens
2025-03-22 18:17:05.189 Status: Netatmo: Station Data parsed
2025-03-22 18:17:05.190 Status: Netatmo: HomeCoach 1
2025-03-22 18:17:05.190 Status: Netatmo: Get HomesData Details
2025-03-22 18:17:05.555 Error: Netatmo: Error data ... {"error":{"code":13,"message":"Application does not have the good scope rights"}}
2025-03-22 18:17:05.555 Status: Netatmo: Home Status Details, size (number of homes) is 0
2025-03-22 18:17:05.556 Status: Netatmo: Status 1

**Comment by JurgenLB** [comment]
> In the latest beta 16583 it seems to work. Although it shows an error about scope rights, that is not very clear. I have an internal station and allowed access of the app to Home Couch. Data seems to be read.
> 
> 2025-03-22 18:14:40.503 Status: Netatmo: Home Status Details, size (number of homes) is 0 2025-03-22 18:14:40.503 Status: Netatmo: Status 1 2025-03-22 18:16:40.168 Status: Netatmo: Worker stopped... 2025-03-22 18:16:58.942 Status: Netatmo: Worker started... 2025-03-22 18:17:03.945 Status: Netatmo: Use refresh token from database... 2025-03-22 18:17:03.946 Status: Netatmo: Requesting refreshed tokens 2025-03-22 18:17:05.189 Status: Netatmo: Station Data parsed 2025-03-22 18:17:05.190 Status: Netatmo: HomeCoach 1 2025-03-22 18:17:05.190 Status: Netatmo: Get HomesData Details 2025-03-22 18:17:05.555 Error: Netatmo: Error data ... {"error":{"code":13,"message":"Application does not have the good scope rights"}} 2025-03-22 18:17:05.555 Status: Netatmo: Home Status Details, size (number of homes) is 0 2025-03-22 18:17:05.556 Status: Netatmo: Status 1

What do you mean by internal station ?
The Netatmo API is telling that you do not have a HomeCoach in your account.

**Comment by JurgenLB** [comment]
@lfzoz I made some changes in the code to see where it goes wrong,
with #6281 
What devices do you have ?

**Comment by JurgenLB** [comment]
@lfzoz I think I found the issue, when the PR is accepted this error should be resolved.

**Comment by nipsgur** [comment]
with built 16586 I could include the sensors from netatmo once again and they seem to update every 15 min (as far as I can see after 1h, some meters change very slow)

What is strange to me, I still get this error message and it comes every 30 seconds. Shouldn't the API be only queried every 15 min?

.
.
.
2025-03-24 16:16:10.644 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 16:16:40.648 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 16:17:10.652 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 16:17:40.656 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 16:18:10.660 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo

**Comment by JurgenLB** [comment]
@nipsgur with that message your m_refreshToken is empty.
Not sure how you can have data.

If the login is not correct the interval is 30 seconds
only when you are correct connected the interval is 15 min.

**Comment by JurgenLB** [comment]
> [@JurgenLB](https://github.com/JurgenLB) I updated the wiki page.

I did re-read the wiki once more.
I believe this is a bit misleading for the moment.
```
And press Accept.
This closes the window and when everything is correct the plugin works.
You get a message that nothing is selected.
Click on the ADD button to add the Netatmo Hardware to Domoticz.
In menu Setup - Devices the connected devices should be shown (can take some time)
```
so add a few empty lines to separate the text, and corrected text;
```
And press Accept.
This closes the window and when everything is correct the plugin works.



If you get a message that nothing is selected.
you can Select the Netatmo-Hardware line and press the login button.


Don't Click on the ADD button to add the Netatmo Hardware to Domoticz.
When you Clink on the Login button and nothing is selected you get a Question if your sure.
**_No device selected, this data will be added as a new device; Do you want to Continue?_**
Click OK and when everything is correct the Hardware is added.


In menu Setup - Devices the connected devices should be shown (can take some time)
```

**Comment by waltervl** [comment]
I am a little bit confused as normally you fill in the gateway settings and press ADD to add the gateway.

Here you fill in the settings, press login (to login Netatmo) and after accept (in Netatmo) you have added the Netatmo hardware gateway to Domoticz? No need to click on ADD button?

And what about the message nothing is selected? Is it a message from Domoticz Netatmo or from Netatmo? 
I think this message is coming because of the strange implementation of the Netatmo hardware gateway. Perhaps you can change the way this is implemented so you need to always use the Domoticz Add or Update button to add or change the gateway?

**Comment by JurgenLB** [comment]
Yes I agree that this is a strange implementation, This was not my work.

The message about nothing is selected is from Domoticz.
![Image](https://github.com/user-attachments/assets/5d4ea9a0-efaa-47ba-b70b-710171f50350)

when you press the ADD button there is a message;
![Image](https://github.com/user-attachments/assets/3377cc3f-a9db-46e6-89d4-804b95f6942a)

so you must Login first before you can ADD, but the Login-button create (Add) the Hardware.

**Comment by nipsgur** [comment]
> [@nipsgur](https://github.com/nipsgur) with that message your m_refreshToken is empty. Not sure how you can have data.
> 
> If the login is not correct the interval is 30 seconds only when you are correct connected the interval is 15 min.

I'm also not sure, how that adds up.
But this is what it looks like in my log:

```
2025-03-24 22:11:13.196 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 22:11:13.196 Status: netatmo_domoticz: Login 0
2025-03-24 22:11:43.199 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 22:11:43.200 Status: netatmo_domoticz: Login 0
2025-03-24 22:12:13.202 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 22:12:13.203 Status: netatmo_domoticz: Login 0
2025-03-24 22:12:14.443 Status: netatmo_domoticz: Station Data parsed living parlour sensor
2025-03-24 22:12:14.443 Status: netatmo_domoticz: Weather 1
2025-03-24 22:12:14.443 Status: netatmo_domoticz: Get HomesData Details
2025-03-24 22:12:14.731 Status: netatmo_domoticz: Home id rugspin updated.
2025-03-24 22:12:14.731 Status: netatmo_domoticz: Home Status Details, size (number of homes) is 1
2025-03-24 22:12:15.250 Status: netatmo_domoticz: Parse Persons
2025-03-24 22:12:15.250 Status: netatmo_domoticz: HomeStatus parsed
2025-03-24 22:12:15.820 Status: netatmo_domoticz: Scenarios Data Recieved
2025-03-24 22:12:15.821 Status: netatmo_domoticz: Status 1
2025-03-24 22:12:43.205 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 22:12:43.206 Status: netatmo_domoticz: Login 0
2025-03-24 22:13:13.209 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 22:13:13.209 Status: netatmo_domoticz: Login 0
2025-03-24 22:13:43.212 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 22:13:43.212 Status: netatmo_domoticz: Login 0
2025-03-24 22:14:13.215 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 22:14:13.215 Status: netatmo_domoticz: Login 0
2025-03-24 22:14:43.218 Error: netatmo_domoticz: No refresh token available; please login to retreive a new one from Netatmo
2025-03-24 22:14:43.218 Status: netatmo_domoticz: Login
```

It throws this error every 30 seconds, and than every 15 min, there is a successful update of the sensors.

**Comment by JurgenLB** [comment]
so Login 0       -> your not logged in
but Weather 1 -> your logged in
and Status 1    -> your logged in

can you enable DEBUG to see wat is happening ?

**Comment by nipsgur** [comment]
> so Login 0 -> your not logged in but Weather 1 -> your logged in and Status 1 -> your logged in
> 
> can you enable DEBUG to see wat is happening ?

I'll try, where was this once again? I have to add a command parameter in the systemd service file?

maybe you give me the command line parameter, which will have the debug info you need. I'm not sure about which I should use -loglevel level_string or -loglevel level_num or -debuglevel level_string or -debuglevel level_num ?

**Comment by JurgenLB** [comment]
if you have domoticz as service

`nano /etc/systemd/system/domoticz.service`

```
      ExecStart=/*/domoticz/domoticz -www 8080 -sslwww 443 -log "/var/log/domoticz-1.log" -loglevel all -debuglevel normal,hardware
#      ExecStart=/*/domoticz/domoticz -www 8080 -sslwww 443 -log "/var/log/domoticz-1.log" -loglevel all
```
you must adapt this to your situation.
And than you can see the LOG-output by;
`sudo tail -f  /var/log/domoticz-1.log`

**Comment by nipsgur** [comment]
ok, I put the debug logging into the domoticz service and restarted domoticz.

After the restart, Now I don't see the 30 seconds error messages any more, which I think is good.
Let's see, if the sensors update after 15 min.

**Comment by nipsgur** [comment]
Ok, now got the usual output in the status as before every 15 min.
```
 2025-03-24 23:07:58.984 Status: netatmo_domoticz: Station Data parsed living parlour sensor
2025-03-24 23:07:58.984 Status: netatmo_domoticz: Weather 1
2025-03-24 23:07:58.985 Status: netatmo_domoticz: Get HomesData Details
2025-03-24 23:07:59.364 Status: netatmo_domoticz: Home id rugspin updated.
2025-03-24 23:07:59.365 Status: netatmo_domoticz: Home Status Details, size (number of homes) is 1
2025-03-24 23:07:59.862 Status: netatmo_domoticz: Parse Persons
2025-03-24 23:07:59.862 Status: netatmo_domoticz: HomeStatus parsed
2025-03-24 23:08:00.222 Status: netatmo_domoticz: Scenarios Data Recieved
2025-03-24 23:08:00.223 Status: netatmo_domoticz: Status 1
.
.
2025-03-24 23:23:00.801 Status: netatmo_domoticz: Station Data parsed living parlour sensor
2025-03-24 23:23:00.802 Status: netatmo_domoticz: Weather 1
2025-03-24 23:23:00.802 Status: netatmo_domoticz: Get HomesData Details
2025-03-24 23:23:01.099 Status: netatmo_domoticz: Home id rugspin updated.
2025-03-24 23:23:01.099 Status: netatmo_domoticz: Home Status Details, size (number of homes) is 1
2025-03-24 23:23:01.672 Status: netatmo_domoticz: Parse Persons
2025-03-24 23:23:01.672 Status: netatmo_domoticz: HomeStatus parsed
2025-03-24 23:23:03.253 Status: netatmo_domoticz: Scenarios Data Recieved
2025-03-24 23:23:03.254 Status: netatmo_domoticz: Status 1 
```

I have to say, I did not restart domoticz after adding the netatmo hardware with the new netatmo app credential, that I made today. So it must have gotten into that strange state just right after adding the netamo hardware.
Now it seems to be fine and working as before.
Thanks a lot for all the effort.

**Comment by waltervl** [comment]
@JurgenLB Updated the Wiki again :-)

**Comment by waltervl** [comment]
Debugging: alternatively stop Domoticz service and start Domoticz manually from command line with the debug options. See for instruction the [Troubleshooting Wiki page](https://wiki.domoticz.com/Troubleshooting#Check_the_Domoticz_log_fileshttps://wiki.domoticz.com/Troubleshooting#Check_the_Domoticz_log_files).

`./domoticz -www 8080 -sslwww 443 -log "/var/log/domoticz.log" -loglevel all -debuglevel normal,auth,hardware,received,webserver,eventsystem,python,thread_id`

**Comment by nipsgur** [comment]
I also encountered the effect, that restarting domoticz could lead to the  "HTTP/2 403" error message.
But as described above, waiting 10-15 min and than do the restart worked to get the Netatmo login back working.

update: it was not working reproducible. After last attempt to restart domoticz, the "HTTP/2 403" error message kept showing up, although I waited 15 min. (Had to make a new app on the netatmo homepage)

**Comment by JurgenLB** [comment]
My test system did also have a block after the 20 min wait. 
so I stopped that system and restart today.

```
2025-03-25 19:38:10.509  Error: Netatmo: Invalid/no data received (refresh tokens)... HTTP/2 403 
2025-03-25 19:38:10.513  Status: Netatmo: Retry LOGIN within 45 min. 
2025-03-25 19:38:10.513  Debug: Netatmo: Refresh Token Flag 1 ...
2025-03-25 19:38:10.513  Status: Netatmo: Login 0

2025-03-25 19:38:21.784  Status: Mainworker Stopped...

2025-03-26 20:09:34.060  Status: Netatmo: Status 1
```

So sometimes the wait is needed and longer or you can make a new App

Kind regards

**Comment by nipsgur** [comment]
@JurgenLB 
I have a technical question, I saw that you are also contributing to the netatmo-api-python package. Is there a difference in how the authentication is done in domoticz compared to netatmo-api-python?

I was playing around with the netatmo-api-python package, because I'm more familiar with python (C/C++ I just only used back in high school)
For the netatmo-api-python package I only made one Netatmo API right in the beginning and I have not seen it getting blocked, even if I make lots of queries in a short time.

With the "REFRESH_TOKEN", how does it work? With the first API call one provides clientId, clientSecret and than you get the "REFRESH_TOKEN" and that is the only chance? After the first API call you have to provide the "REFRESH_TOKEN" correctly?

**Comment by JurgenLB** [comment]
Yes I did also some work for the netatmo-api-python package to have the New API integration.
I don't know the difference.
But for Domoticz;
The authentication now have a function in 'www/app/hardware/Hardware.js' that makes a login and have a Access-token and Refresh-token.

This refresh-token is put in the database.

And the second authentication is from the plugin to get a Access-token with the refresh-token from the database.

so this gives 2 authentications close after each other.

I believe this can result in the blocking loop from Netatmo.

so moving the function 'OnNetatmoLogin' from Hardware.js to Netatmo.cpp can possibly solve the problem but both files need to be able to use the function.

Kind regards

**Comment by lfzoz** [comment]
I currently updated to beta 16594. I have smart indoor monitor. The annoying on beta is, that after each domoticz update netatmo stops working, after manual reauthentication it says:
 2025-03-28 22:10:21.155 Status: Netatmo: Use refresh token from database...
2025-03-28 22:10:21.156 Status: Netatmo: Requesting refreshed tokens
2025-03-28 22:10:21.558 Error: Netatmo: Invalid/no data received (refresh tokens)... HTTP/2 403
2025-03-28 22:10:21.558 Status: Netatmo: Retry LOGIN within 45 min.
2025-03-28 22:10:21.559 Status: Netatmo: Login 0 
So, I will stop domoticz and wait 45 minute (can this be automated?). 
Last time it worked after 45 minutes with some scope error, but worked.  Is the netatmo plugin working in stable version as well?
L.

**Comment by waltervl** [comment]
@lfzoz if you switch off the automatic update check on Domoticz you dont need to restart after every update. Do not switch back to stable as that probably give a lot of other issues.
Switch off the update check in Domoticz menu Setup - Settings. You can always manually check for an update if needed to update Netatmo Authentication features/bug fixing through menu Setup - check for Update.

**Comment by gizmocuz** [comment]
@JurgenLB , do you store the refresh_token as uservariable? (see the recent TADO changes)

The log seems wrong, maybe the steps are wrong

- Use refresh token from database (that's ok)
- Requesting refreshed token (you mean, requesting access_token)

Could you check what goes wrong and why you receive a 403? Maybe there is more data in the response (headers/body)

In RefreshToken (I would name it Refresh(Or Request)AccessToken,
There is a line where you check if access_token, expires_in, or refresh_token is empty,
if that is the case, you store the (empty/wrong?) refresh token, that does not seem correct

And you should always get a access_token/refresh_token with that call, otherwise there is a API issue
Not sure what you do with the 'expires_in' time... this is in seconds? why not mytime(nullptr) + expires, or mytime(nullptr) + (expires-60), to be safe?

StoreRequestTokenFlag does not store 'token', it stores a flag?

Please have a look at the recent TADO changes, I like the idea of storing the token (only the refresh token) in the hardware table, I am going to do this as well

**Comment by gizmocuz** [comment]
I had a small peek in the code and made some tiny changes (nothing really changed, except the bForce check in **RefreshToken**)

I don't think the URL in NETATMO_OAUTH2_TOKEN_URI should contain a questionmark (?)

The NETATMO_OAUTH2_TOKEN_URI content could end with /api/ so you do not have to add this 20 times in **MakeRequestURL** and at the end you should not need to add a questionark

Instead of a stringstream you can use

std::string szUrl(NETATMO_API_URI);

and lines like

szUrl += "getmeasure";

Maybe instead of calling Login() all the time in every function, only do this when needed (once?)
(do_work?)
And in the function check if there is a access_token

In Do_Work you always call 'RefreshToken', but this is only needed at startup of the hardware (with the refresh_token), or if the access_token expires (refresh_token expiration), or when there is a API error return about invalid access/token

bFirstTimeWS, bFirstTimeHS, bFirstTimeSS, and (bFirstTimeTH) is always true, maybe use one variable (bFirstTime) ?

There is a lot going on in 'RefreshToken', when there is no json returned, I think this is an error and Netamo is always returning json?
So maybe just return here? (false)

Next, check if there is an error, log this, check if it is about authorization (invalid refresh_token), if yes, force a login again

**Comment by lfzoz** [comment]
Ok, the rest of the story is. After the upgrade i stopped the domoticz and started it in 45 minutes:
 sleep 3000 ; sudo service domoticz start
But it seems, it doesn't work again. I'll try to repeat the process again: login, authorize, stop, start in 45 minutes i hope it helps

Mar 28 22:14:09 domoticz domoticz: Netatmo: Worker stopped...
Mar 28 23:00:04 domoticz domoticz: Netatmo: Worker started...
Mar 28 23:00:09 domoticz domoticz: Netatmo: Use refresh token from database...
Mar 28 23:00:09 domoticz domoticz: Netatmo: Requesting refreshed tokens
Mar 28 23:00:09 domoticz domoticz: Netatmo: Invalid/no data received (refresh tokens)... HTTP/2 403
Mar 28 23:00:09 domoticz domoticz: Netatmo: Retry LOGIN within 45 min.
Mar 28 23:00:09 domoticz domoticz: Netatmo: Login 0
Mar 28 23:35:09 domoticz domoticz: Netatmo: Use refresh token from database...
Mar 28 23:35:09 domoticz domoticz: Netatmo: Requesting refreshed tokens
Mar 28 23:35:10 domoticz domoticz: Netatmo: Invalid/no data received (refresh tokens)... HTTP/2 403
Mar 28 23:35:10 domoticz domoticz: Netatmo: Retry LOGIN within 45 min.
Mar 28 23:35:10 domoticz domoticz: Netatmo: Login 0

**Comment by pipiche38** [comment]
same here! you are not alone

**Comment by JurgenLB** [comment]
@gizmocuz there are 2 URI variable in the code, the NETATMO_OAUTH2_TOKEN_URI 
`https://api.netatmo.com/oauth2/token?`
and the NETATMO_API_URI
`https://api.netatmo.com/`
for a endpoint the URI is
`https://api.netatmo.com/api/getpublicdata?`


![Image](https://github.com/user-attachments/assets/b9601d03-e79e-4056-8ab5-9a9cda081a94)


I was thinking to have
1 variable with
`#define NETATMO_API_URI "https://api.netatmo.com/"`
and then
`std::string httpUrl(NETATMO_API_URI + "oauth2/token?")`
and
`std::string httpUrl(NETATMO_API_URI + "api/getmeasure?" + data)`

The `login()` is from the old code, I just left it. but it is only in SetProgramState, SetDimmerState, SetSchedule, SetSetpoint to make sure we are Logged in when we write to Hardware.

Than in  Do_Work it is used 1 time.

the Oauth2 is not my work, but I'm trying to solve this.

**Comment by gizmocuz** [comment]
And we appreciate your effort!

**Comment by JurgenLB** [comment]
with my test system I now have to add `http://10.0.1.142:8080/` as redirect URI  on the dev.netatmo.com
and then it works. Now I'm with family butt I will recheck later

**Comment by JurgenLB** [comment]
@waltervl sorry but can you replace the previous picture in the wiki.

![Image](https://github.com/user-attachments/assets/1f9c75d4-8899-40fc-936a-99e8cf4c607b)

as the previous is not correct. People does neet to modify the IP to their situation.

**Comment by lfzoz** [comment]
beta 16594 seems to work, thank you. i didn't change the URI - it's left empty. 
Mar 29 10:46:26 domoticz domoticz: Netatmo: Worker stopped...
Mar 29 11:00:04 domoticz domoticz: Netatmo: Worker started...
Mar 29 11:00:09 domoticz domoticz: Netatmo: Requesting new access_token
Mar 29 11:00:10 domoticz domoticz: Netatmo: We refreshed our token ...
Mar 29 11:00:10 domoticz domoticz: Netatmo: Login 1
Mar 29 11:00:12 domoticz domoticz: Netatmo: Station Data parsed Netatmo
Mar 29 11:00:12 domoticz domoticz: Netatmo: HomeCoach 1

**Comment by waltervl** [comment]
> [@waltervl](https://github.com/waltervl) sorry but can you replace the previous picture in the wiki.
> 
> ![Image](https://github.com/user-attachments/assets/1f9c75d4-8899-40fc-936a-99e8cf4c607b)
> 
> as the previous is not correct. People does neet to modify the IP to their situation.

I can, but what is the IP in the redirect URL ? Some Netatmo device? The Domoticz server?

**Comment by JurgenLB** [comment]
According the documentation the redirect URI is mandatory, but leaving I empty seems to work for some users.

The redirect URI is the IP and Port from domoticz.
In my case IP 10.0.1.142 and Port 8080 but others need to adapt this to their situation.

when comparing to Netatmo-api-python I found that there is the use of `Content-Type","application/x-www-form-urlencoded;charset=utf-8`

and in the plugin there is the use off `Content-Type","application/x-www-form-urlencoded;charset=UTF-8`


this is from the documentation 

![Image](https://github.com/user-attachments/assets/183417e9-c84f-470e-bc21-12fd44424688)

kind regards

**Comment by Cadkey** [comment]
Hello
If it can help, I have a PHP script that makes requests every minute without any problem.
The header is like this:
`'header' => 'Content-type: application/x-www-form-urlencoded;charset=UTF-8'."\r\n".'User-Agent: netatmoclient',`
But I dont need this step 4 to connect to the API.

**Comment by JurgenLB** [comment]
@Cadkey what I use is the documentation on dev.netatmo.com but I will try your suggestion

**Comment by JurgenLB** [comment]
what I have found is that if I just let it run and after the first block just wait 45 min then it keeps blocking,
but if I manually stop and start after 15-20 min. the login with the refresh-token is correct.

So I believe that the HTTP-Client is not completely closing the session and this result in the blocking.

**Comment by Cadkey** [comment]
I don't know the code used by the plugin and I only know PHP, sorry.
The strange thing about this problem is that the authentication isn't complex and hasn't changed in two years.
There was a bug on URL requests two weeks ago, but it was fixed by Netatmo within a few hours.
There was no bug on cURL requests.
Netatmo has been enforcing request quotas for two weeks. Before, quotas weren't enforced.

A working PHP code example:
https://github.com/KiboOst/php-simpleNetatmoAPI/blob/master/class/splNetatmoAPI.php

Expire_in is not handled. I proposed a modification that I'm using:
https://github.com/KiboOst/php-simpleNetatmoAPI/issues/20

**Comment by JurgenLB** [comment]
> I don't know the code used by the plugin and I only know PHP, sorry. The strange thing about this problem is that the authentication isn't complex and hasn't changed in two years. There was a bug on URL requests two weeks ago, but it was fixed by Netatmo within a few hours. There was no bug on cURL requests. Netatmo has been enforcing request quotas for two weeks. Before, quotas weren't enforced.
> 
> A working PHP code example: https://github.com/KiboOst/php-simpleNetatmoAPI/blob/master/class/splNetatmoAPI.php
> 
> Expire_in is not handled. I proposed a modification that I'm using: [KiboOst/php-simpleNetatmoAPI#20](https://github.com/KiboOst/php-simpleNetatmoAPI/issues/20)

I believe Netatmo has certainly made changes in the last year / months,
for example

![Image](https://github.com/user-attachments/assets/859a5bee-2b03-4c73-a5b5-100e6d6c8417)

I have looked at your script but when I use all the scope without the combined devices, so for example use Doorbell-scope and thermostat-scopes for only a thermostat than this fails when I was trying to adapt the new API.

It is possible that you use a Old way and they still support that for existing systems.

Kind regards

**Comment by Cadkey** [comment]
There's a member who created his PHP less than two months ago, and it works perfectly for him, Phil35. 
I recreated my Netatmo apps two days ago to do some testing, and it works.
On the web, it seems that only Domoticz isn't working.

**Comment by JurgenLB** [comment]
I now have tried with a separate instance off cUrl in Netatmo.cpp and then I can start/stop immediately.

`2025-03-31 06:50:33.556  Status: Legrand: Status 1

2025-03-31 06:51:04.823  Status: Mainworker Stopped...
2025-03-31 06:51:10.943  Status: Domoticz V2025.1 (build 16623) (c)2012-2025 GizMoCuz

2025-03-31 06:51:13.033  Status: Netatmo: Worker started...

2025-03-31 06:51:18.034  Status: Netatmo: Requesting new access_token

2025-03-31 06:51:26.855  Status: Netatmo: Status 1`

so there must be an issue with HTTPClient on domoticz.

Kind regards

**Comment by gizmocuz** [comment]
Well, let's assume this is not a Domoticz issue.

As I mentioned in my previous comment, the first thing the class should do at startup is to get a new access_token from the refresh_token API call.
(And store the new refresh token for later usage)

This is also done by the PHP example above

It is also worth noting that users have to create a second application if they want to use another script (like the above PHP script), don't use the same app/client secret/refresh token in both implementations

I would suggest you have a look into the TADO.cpp code where oauth2 is also implemented, and is also checking for the expiration of the access_token

So steps are
- At launch (StartHardware) get a new refresh_token, store the new refresh token (in the database), and store the expiration time in a variable
- in the loop, check if the access_token expiration time has expired (subtract a minute, if it is 10 minutes, use 9) and call the function to refresh a new access_token (same as StartHardware)
- use the access_token for all API calls

**Comment by pipiche38** [comment]
What I can confirm is

- with the old build stable - 2024.7 and doing the manual things to get the "password" it works like a charm.

With build 2025.1 16598 - from docker , this is not working. It is even more complicated now, with the changes done on the Hardware page, where you have to reload the page.

**Comment by JPGNT** [comment]
I just tested beta 16607 on Windows and for the moment everything works fine but with an error message at startup:
 NETATMO: Error data ... {"error":{"code":500,"message":"Internal Server Error"}}

**Comment by JurgenLB** [comment]
I now have the next_refreshTime stored in the address-field of the Hardware.
But also experience the block.
Then I change the useragent in httpclient and rebuild.
Then it runs and connect.
I'm not convinced the rebuild was the solution or the change off useragent.

Kind regards

**Comment by lacha07** [comment]
Hello, I just pulled the latest Docker build 16608, and on my two houses, I’m connected again with Netatmo. Thanks for that!
The only glitch is that the plugin sees only one of my houses, not both.

**Comment by waltervl** [comment]
Comment of chrominator on the forum: https://forum.domoticz.com/viewtopic.php?p=324919#p324919

> I did a try on the last source available, domoticz Version: 2025.1 (build 16609).
> 
> Since I've altered the source by displaying the values of the http posting to renew the token, I've copied the content of httpData from the log to use it with curl on a terminal, specifying the right headers with -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8".
> While the reply in domoticz was "Error: Netatmo: Invalid/no data received (refresh tokens)... HTTP/2 403", the outcome from curl was every time a valid refreshed token.
> 
> So that implies that the httpData content is the right one. Other parameters are the headers passed to the http posting.
> **My try was to comment the line where the http headers are assigned to ExtraHeaders variable on line 362.**
> 
> Compilation and run.
> Everything went fine, netatmo contacted and all devices updated.
> Restart the hardware, same result, all is fine.
> Reboot the computer, same result, everything ok.
> 
> I'm the opposite of an expert in C++ and http posting, my only concern here is to share my try and maybe to inspire a track to follow to fix this netatmo issue.

**Comment by nipsgur** [comment]
again a little of topic:

Has someone a direct link to the info from Netatmo on how the rain data are organized in Netatmo and how to recover the correct amount of rain from it?

In detail the data from Netatmo looks a bit inconsistent to me (I query them every 10 min, maybe that is not the correct interval length, but in principle it should not matter).

As far as I understood, the rain_1h and rain_24h should be a rolling sum of the last 1h and last 24h.

What I see is:
1) rain_24 is not really a rolling sum, but the accumulated rain for just one day starting at 00:00 am and is always reset to zero at 00:00 pm

2) rain_1h is something like a rolling sum over the last 1h, but it is not really consistent and I would sometimes get negative amount of rain or it does not fully drop to zero, if there was no rain for more than 1h when I recover the amount of rain from it.

Sorry, I mixed some plots, domoticz calculates the amount of rain for a day correctly.
But I would still like to understand, how to handle the rain_1h data?

**Comment by Chrominator** [comment]
> Comment of chrominator on the forum: https://forum.domoticz.com/viewtopic.php?p=324919#p324919
> 
> > I did a try on the last source available, domoticz Version: 2025.1 (build 16609).
> > Since I've altered the source by displaying the values of the http posting to renew the token, I've copied the content of httpData from the log to use it with curl on a terminal, specifying the right headers with -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8".
> > While the reply in domoticz was "Error: Netatmo: Invalid/no data received (refresh tokens)... HTTP/2 403", the outcome from curl was every time a valid refreshed token.
> > So that implies that the httpData content is the right one. Other parameters are the headers passed to the http posting.
> > **My try was to comment the line where the http headers are assigned to ExtraHeaders variable on line 362.**
> > Compilation and run.
> > Everything went fine, netatmo contacted and all devices updated.
> > Restart the hardware, same result, all is fine.
> > Reboot the computer, same result, everything ok.
> > I'm the opposite of an expert in C++ and http posting, my only concern here is to share my try and maybe to inspire a track to follow to fix this netatmo issue.

Sorry, wrong track, I was probably lucky when doing this. 
Now netatmo fails as usual, even with the exec made yesterday.

[Full text in the forum](https://forum.domoticz.com/viewtopic.php?p=324949#p324949)

**Comment by Cadkey** [comment]
Hello,
Have you checked that refresh_token isn't modified at the same time as access_token?
When 'expire_in' expires, I always save access_token **and** refresh_token.
I don't use the four-step method, in my case both tokens change upon expiration.

**Comment by Chrominator** [comment]
Possibly fixed thank to this [PR](https://github.com/domoticz/domoticz/pull/6293#issue-2974129814)
Works for me after several restart/reboot/new connections.

**Comment by waltervl** [comment]
> Possibly fixed thank to this [PR](https://github.com/domoticz/domoticz/pull/6293#issue-2974129814) Works for me after several restart/reboot/new connections.

Changed into PR https://github.com/domoticz/domoticz/pull/6296 and implemented in latest beta 16619

**Comment by JL-Dive** [comment]
on 16625 improvement: now it s login and get information but its not stable
after a time i get 

2025-04-08 01:26:39.562 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/getstationsdata?&get_favorites=true&, response: {"error":{"code":3,"message":"Access token expired"}}
2025-04-08 01:26:39.756 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/gethomecoachsdata?&get_favorites=true&, response: {
2025-04-08 01:26:39.756 "error": {
2025-04-08 01:26:39.756 "code": 3,
2025-04-08 01:26:39.756 "message": "Access token expired"
2025-04-08 01:26:39.756 }
2025-04-08 01:26:39.756 }
2025-04-08 01:26:40.012 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/homesdata?&get_favorites=true&, response: {"error":{"code":3,"message":"Access token expired"}}

it repeat every 15 minutes

if i update domoticz hardware. it restart to work

**Comment by Cadkey** [comment]
Coincidence or not, your error seems to be related to this delay:
https://github.com/domoticz/domoticz/issues/6280#issuecomment-2749154714
I don't understand the delays used in the plugin, Netatmo API only uses expire_in.
I query the API every minute without error. When expire_in expires, I regenerate the tokens.
Here's my method:
when creating the tokens, I save the timestamp corresponding to the time without the seconds, for exemple 13:42:00 if the exact time is 13:42:05.
I read expire_in, which normally is 10800 upon creation, but I always read the value as a precaution.
In the example, as long as the time (corresponding timestamp) is less than 16:42:00, the tokens are valid, otherwise I renew them.
**I test this with each request.**
This has always worked 100% for me since implementing Auth2 and its developments.
It's very simple, it meets the connection requirements.

**Comment by nipsgur** [comment]
> on 16625 improvement: now it s login and get information but its not stable after a time i get
> 
> 2025-04-08 01:26:39.562 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/getstationsdata?&get_favorites=true&, response: {"error":{"code":3,"message":"Access token expired"}} 2025-04-08 01:26:39.756 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/gethomecoachsdata?&get_favorites=true&, response: { 2025-04-08 01:26:39.756 "error": { 2025-04-08 01:26:39.756 "code": 3, 2025-04-08 01:26:39.756 "message": "Access token expired" 2025-04-08 01:26:39.756 } 2025-04-08 01:26:39.756 } 2025-04-08 01:26:40.012 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/homesdata?&get_favorites=true&, response: {"error":{"code":3,"message":"Access token expired"}}
> 
> it repeat every 15 minutes
> 
> if i update domoticz hardware. it restart to work

same for me, initially it works after restarting domoticz, but after 2-3 hours I get the same error messages.

**Comment by Cadkey** [comment]
It seems to work for some but not for all.
Maybe related to the timestamp calculation and the request every 15 minutes (crontab) ?
This is the possible reason for repeated malfunction around 3 hours of use.

**Comment by JPGNT** [comment]
Avec la 16625 sous Windows, j'obtiens ces messages plusieurs fois par jour, mais le process se relance et je n'ai pas de trou dans les données:

2025-04-09 13:03:48.107 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/getstationsdata?&get_favorites=true&, response: {
2025-04-09 13:03:48.107 "error": {
2025-04-09 13:03:48.107 "code": 3,
2025-04-09 13:03:48.107 "message": "Access token expired"
2025-04-09 13:03:48.107 }
2025-04-09 13:03:48.107 }
2025-04-09 13:03:48.154 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/homesdata?&get_favorites=true&, response: {
2025-04-09 13:03:48.154 "error": {
2025-04-09 13:03:48.154 "code": 3,
2025-04-09 13:03:48.154 "message": "Access token expired"
2025-04-09 13:03:48.154 }
2025-04-09 13:03:48.154 }

**Comment by gizmocuz** [comment]
Yes, I think the normal access token is valid for 15 minutes. So it seems the calculation of the expiration of this does not seem to work correctly

**Comment by JurgenLB** [comment]
There was a error in the refreshToken-code I changed this with #6297

**Comment by JPGNT** [comment]
Hello,

Toutes les 3 heures avec la 16627 sous Windows.

2025-04-11 08:48:55.775 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/getstationsdata?&get_favorites=true&, response: {
2025-04-11 08:48:55.775 "error": {
2025-04-11 08:48:55.775 "code": 3,
2025-04-11 08:48:55.775 "message": "Access token expired"
2025-04-11 08:48:55.775 }
2025-04-11 08:48:55.775 }
2025-04-11 08:48:56.020 Error: NETATMO: Error data ... url: https://api.netatmo.com/api/homesdata?&get_favorites=true&, response: {
2025-04-11 08:48:56.020 "error": {
2025-04-11 08:48:56.020 "code": 3,
2025-04-11 08:48:56.020 "message": "Access token expired"
2025-04-11 08:48:56.020 }
2025-04-11 08:48:56.020 }

Mais ce n'est qu'un défaut "esthétique" car sinon tout marche bien.

Merci pour vos efforts.

**Comment by JurgenLB** [comment]
Thank you for the appriciation, It's a bigger project than I initially thought.
When my PR works for everyone it's a happy Easter.

Kinds regards

**Comment by lfzoz** [comment]
Hi,

happy easter and thank you for all the work you do for us.

In the 16626 it works for 3 hours after hitting hardware/netatmo/update button.

Apr 24 11:08:26 domoticz domoticz: Netatmo: We refreshed our token ...
Apr 24 11:08:26 domoticz domoticz: Netatmo: Login 1
Apr 24 11:08:26 domoticz domoticz: Netatmo: Station Data parsed Netatmo
Apr 24 11:08:26 domoticz domoticz: Netatmo: Temp + Humidity + Baro (NA: Obyvacka)
Apr 24 11:08:26 domoticz domoticz: Netatmo: HomeCoach 1
Apr 24 11:08:26 domoticz domoticz: Netatmo: Air Quality (NA: CO2)
Apr 24 11:08:26 domoticz domoticz: Netatmo: General/Sound Level (NA: Hluk)

after cca 3 hours:

Apr 24 14:13:51 domoticz domoticz: Netatmo: Error data ...  url: https://api.netatmo.com/api/gethomecoachsdata?&get_favorites=true&, response: {#015#012  "error": {#015#012    "code": 3,#015#012    "message": "Access token expired"#015#012  }#015#012}
Apr 24 14:13:51 domoticz domoticz: Netatmo: HomeCoach 1

Is there solution for that already?

**Comment by nipsgur** [comment]
tried the build 16656 yesterday and it worked with the existing netatmo API app.
It is running now much longer than 3h (~15h) and so far no "message": "Access token expired".
Thanks for all the effort.

**Comment by lfzoz** [comment]
I upgraded to 16657 and it seems to works fine for 2 days. So I will observe it further. Thank you for.

**Comment by waltervl** [comment]
@pipiche38  @Chrominator @nipsgur @JPGNT @JL-Dive @JurgenLB 
Did updating to the latest beta ( >=16656) solve this issue for you? Is Netatmo integration running stable now? 
And can this issue be closed?

**Comment by JPGNT** [comment]
I don't know how to say for the 16656 because I haven't installed it. On the other hand, everything is OK with the 16567.  At this time, the problem is solved at home.
Thank you to everyone who has worked the subject.

**Comment by JurgenLB** [comment]
For me this is running and this issue can be closed.

Maybe even #6036 can be closed 

Kind regards

**Comment by rene2716** [comment]
Indeed all fine, thanks for the great job on this
